KierenP/Halogen

Halogen/src/Evaluate.cpp, Halogen/src/Evaluate.h, Halogen/src/Search.cpp
Bench 26774098
```
move_order_piece_values vs master DIFF
ELO   | 3.59 +- 7.26 (95%)
SPRT  | 12.0+0.12s Threads=1 Hash=8MB
LLR   | 0.44 (-2.94, 2.94) [0.00, 5.00]
Games | N: 6096 W: 2147 L: 2084 D: 1865
```
=> Used evaluation values for move ordering

Halogen/src/Makefile, Halogen/src/TranspositionTable.cpp, Halogen/src/TranspositionTable.h
Small regression permitted for confidence in thread safety. 
```
thread_safety vs master DIFF
ELO   | -13.36 +- 11.55 (95%)
LLR   | -2.03 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2394 W: 778 L: 870 D: 746
```
=> Thread safety

Halogen/src/TTEntry.cpp, Halogen/src/TTEntry.h, Halogen/src/main.cpp
```
transposition_16byte vs master DIFF
ELO   | 8.59 +- 6.10 (95%)
Games | N: 8572 W: 3063 L: 2851 D: 2658
```
=> Transposition 16byte

Halogen/src/Search.cpp, Halogen/src/TranspositionTable.cpp, Halogen/src/TranspositionTable.h
```
transposition_access_clean vs master DIFF
ELO   | 1.95 +- 3.72 (95%)
LLR   | 5.25 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 22976 W: 7974 L: 7845 D: 7157
```
=> Transposition access clean

Halogen/src/Search.cpp, Halogen/src/Search.h
Bench: 15110009
```
history_each_side vs master DIFF
ELO   | 15.14 +- 8.65 (95%)
Games | N: 4224 W: 1532 L: 1348 D: 1344
```
=> Changed history tables to have one for each player

Halogen/src/Search.cpp
```
quiet_history vs master DIFF
ELO   | 13.11 +- 7.96 (95%)
Games | N: 4984 W: 1792 L: 1604 D: 1588
```
=> Only update history if the move is quiet

Halogen/src/Search.cpp, Halogen/src/Search.h, Halogen/src/TimeManage.cpp, Halogen/src/main.cpp
```
smp_aspiration vs master DIFF
ELO   | 55.29 +- 24.54 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 10.00]
Games | N: 526 W: 215 L: 132 D: 179
```
=> SMP depth skip

Halogen/src/Search.cpp, Halogen/src/TranspositionTable.cpp, Halogen/src/TranspositionTable.h
```
lockless_smp vs master DIFF
ELO   | 14.24 +- 10.62 (95%)
SPRT  | 5.0+0.05s Threads=6 Hash=64MB
LLR   | 2.98 (-2.94, 2.94) [0.00, 10.00]
Games | N: 2758 W: 980 L: 867 D: 911
```
=> Lockless smp

Halogen/src/TranspositionTable.cpp
Bench: 12140859
```
prefetch_gcc vs master DIFF
ELO   | 10.03 +- 8.01 (95%)
SPRT  | 5.0+0.05s Threads=6 Hash=64MB
LLR   | 2.97 (-2.94, 2.94) [0.00, 10.00]
Games | N: 4711 W: 1603 L: 1467 D: 1641
```
=> Added prefetch intrinsic for gcc complies

Halogen/src/Search.cpp, Halogen/src/Search.h, Halogen/src/main.cpp
```
Extended_LMR vs master DIFF
ELO   | 8.27 +- 6.65 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 10.00]
Games | N: 6848 W: 2321 L: 2158 D: 2369
```
=> Extended LMR

Halogen/src/Search.cpp
```
Bench: 4354534
extension_LMR vs master DIFF
ELO   | 13.50 +- 10.05 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 10.00]
Games | N: 2704 W: 848 L: 743 D: 1113
```
=> Allow LMR for extended plys

Halogen/src/Search.cpp
```
Bench: 3635209
LMR_equal_alpha vs master DIFF
ELO   | 11.46 +- 8.90 (95%)
LLR   | 2.95 (-2.94, 2.94) [0.00, 10.00]
Games | N: 3456 W: 1077 L: 963 D: 1416
```
=> Allow LMR when score equals alpha

Halogen/src/Search.cpp
```
Bench: 3635209
futility_prune_enhance vs master DIFF
ELO   | 1.31 +- 7.32 (95%)
LLR   | 3.04 (-2.94, 2.94) [-10.00, 0.00]
Games | N: 4768 W: 1324 L: 1306 D: 2138
```
=> Small non-functional speedup

Halogen/src/Search.cpp
```
Bench: 3481729
ELO   | 13.16 +- 9.65 (95%)
LLR   | 3.01 (-2.94, 2.94) [0.00, 10.00]
Games | N: 2720 W: 794 L: 691 D: 1235
```
=> Variable null reduction depth

Halogen/src/Search.cpp
```
Bench: 3502525
lmr_endgame vs master DIFF
ELO   | 0.87 +- 5.66 (95%)
LLR   | -2.97 (-2.94, 2.94) [0.00, 10.00]
Games | N: 7944 W: 2197 L: 2177 D: 3570
```
=> Disallow LMR in KPvKP endgames

Halogen/src/Search.cpp
```
rebel_IID vs master DIFF
ELO   | 1.67 +- 5.05 (95%)
LLR   | -2.99 (-2.94, 2.94) [0.00, 10.00]
Games | N: 10424 W: 3022 L: 2972 D: 4430
```
=> Implement IID reduction by Rebel

Halogen/src/Evaluate.cpp, Halogen/src/texel.cpp
```
eval_mobility vs master DIFF
ELO   | 3.17 +- 3.20 (95%)
LLR   | -3.03 (-2.94, 2.94) [0.00, 10.00]
Games | N: 26528 W: 7900 L: 7658 D: 10970
```
=> Added mobility for all pieces

Halogen/src/Network.h, Halogen/src/Position.cpp
```
ELO   | -1.67 +- 7.91 (95%)
LLR   | -2.97 (-2.94, 2.94) [0.00, 10.00]
Games | N: 4356 W: 1273 L: 1294 D: 1789
```
Even though it suggests that it may be a tiny regression, testing shows that the bench is in fact faster and I doubt it has drastic side effects. Int makes more intuitive sense and I think in this case is more correct. Possibly revisit in future.
=> Bench: 7072296

Halogen/src/Network.cpp, Halogen/src/Position.cpp
```
net_uAdi7tSlFB vs eval_net DIFF
ELO   | 24.59 +- 15.17 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 10.00]
Games | N: 1302 W: 464 L: 372 D: 466
```
=> Bench: 6903401

Halogen/src/Position.cpp
```
net_nxtc9owQ2i vs master DIFF
ELO   | 11.88 +- 9.22 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 10.00]
Games | N: 3540 W: 1209 L: 1088 D: 1243
```
=> Bench: 7209513

Halogen/src/Search.cpp
```
ELO   | 5.26 +- 7.33 (95%)
LLR   | 0.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 6738 W: 2684 L: 2582 D: 1472
```
=> Use log transformation for SMP aspiration widths 

Halogen/src/Move.cpp, Halogen/src/Move.h, Halogen/src/MoveOrder.cpp, Halogen/src/MoveOrder.h, Halogen/src/Search.cpp
```
ELO   | 7.68 +- 5.56 (95%)
Games | N: 9456 W: 3090 L: 2881 D: 3485
```
=> Faster sort

Halogen/src/Search.cpp, Halogen/src/Search.h
```
ELO   | 8.18 +- 5.97 (95%)
Games | N: 9646 W: 3689 L: 3462 D: 2495
```
Also tested for non regression in single threaded games
```
ELO   | 6.60 +- 6.98 (95%)
Games | N: 6000 W: 1952 L: 1838 D: 2210
```
=> Keep threads searching if at least one other thread is still searching

Halogen/src/main.cpp
```
ELO   | 5.18 +- 4.10 (95%)
Games | N: 17168 W: 5475 L: 5219 D: 6474
```
=> Blitz time allocation

Halogen/src/EvalNet.cpp
Bench: 6612922
```
ELO   | 23.74 +- 11.06 (95%)
Games | N: 2448 W: 870 L: 703 D: 875
```
=> Add tempo parameter to the evaluation function

Halogen/src/EvalNet.cpp
Bench: 6189619
```
ELO   | 27.81 +- 11.95 (95%)
Games | N: 2016 W: 703 L: 542 D: 771
```
=> Scale NN output by 1.3x

Halogen/src/Search.cpp
Bench: 6258688
```
ELO   | 3.39 +- 2.63 (95%)
Games | N: 40528 W: 12524 L: 12129 D: 15875
```
=> Use a default aspiration window size of 20

Halogen/src/Search.cpp, Halogen/src/Search.h
Bench: 6258688
```
ELO   | 2.99 +- 5.30 (95%)
Games | N: 10122 W: 3156 L: 3069 D: 3897
```
```
ELO   | -4.35 +- 3.46 (95%)
SPRT  | 20.0+0.2s Threads=8 Hash=256MB
LLR   | -2.95 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 18610 W: 4363 L: 4596 D: 9651
```
Small regression acceptable.
=> Simplify SMP depth skiping

Halogen/src/Search.cpp
Bench: 6144000
```
ELO   | 6.98 +- 5.18 (95%)
Games | N: 10704 W: 3432 L: 3217 D: 4055
```
=> Use default aspiration window width of 15

Halogen/src/Search.cpp
Bench: 6144000
```
ELO   | 2.78 +- 5.13 (95%)
LLR   | 3.03 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 10736 W: 3323 L: 3237 D: 4176
```
=> Always seach to a depth of 1 in time panic

Halogen/src/Search.cpp, Halogen/src/TimeManage.cpp, Halogen/src/TimeManage.h, Halogen/src/main.cpp
Bench: 6144000
```
ELO   | 20.94 +- 11.04 (95%)
Games | N: 2176 W: 686 L: 555 D: 935
```
```
ELO   | 2.93 +- 5.27 (95%)
Games | N: 10208 W: 3166 L: 3080 D: 3962
```
=> Fix the maximum allocated time to avoid time losses

Halogen/src/main.cpp
Bench: 6144000
Tested as various time controls:
```
ELO   | 0.99 +- 7.57 (95%)
LLR   | 2.96 (-2.94, 2.94) [-10.00, 0.00]
Games | N: 4920 W: 1508 L: 1494 D: 1918
```
```
ELO   | 4.43 +- 10.00 (95%)
SPRT  | 10.0+0.0s Threads=1 Hash=8MB
LLR   | 3.06 (-2.94, 2.94) [-10.00, 0.00]
Games | N: 3136 W: 1082 L: 1042 D: 1012
```
```
ELO   | 17.27 +- 15.58 (95%)
SPRT  | 40/10.0s Threads=1 Hash=8MB
LLR   | 3.02 (-2.94, 2.94) [-10.00, 0.00]
Games | N: 1248 W: 437 L: 375 D: 436
```
=> Refactor time

Halogen/src/Search.cpp
Reverts KierenP/Halogen#139
```
ELO   | -5.75 +- 14.76 (95%)
LLR   | -0.51 (-2.94, 2.94) [0.00, 5.00]
Games | N: 1088 W: 269 L: 287 D: 532
```
Demonstrated to be a regression at LTC
=> Revert "Use more aggressive LMR"

Halogen/src/Search.cpp
```
ELO   | 3.12 +- 5.25 (95%)
LLR   | 3.06 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 10128 W: 3107 L: 3016 D: 4005
```
```
ELO   | 3.42 +- 4.93 (95%)
LLR   | 3.08 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 9344 W: 2342 L: 2250 D: 4752
```
=> Remove search extension from pawns reaching 7th rank

Halogen/src/Search.cpp
```
ELO   | 0.63 +- 3.88 (95%)
Games | N: 18624 W: 5653 L: 5619 D: 7352
```
```
ELO   | 5.31 +- 4.75 (95%)
LLR   | 2.19 (-2.94, 2.94) [0.00, 5.00]
Games | N: 10208 W: 2618 L: 2462 D: 5128
```
=> Remove check extensions for non PV branches

Halogen/src/Search.cpp
Bench: 4988928
```
ELO   | 1.01 +- 3.45 (95%)
LLR   | -1.45 (-2.94, 2.94) [0.00, 5.00]
Games | N: 23056 W: 6891 L: 6824 D: 9341
```
```
ELO   | -1.26 +- 3.56 (95%)
LLR   | 0.61 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 17376 W: 4115 L: 4178 D: 9083
```
=> Do not save results to TT in quiescence search

Halogen/src/Search.cpp
```
ELO   | 116.64 +- 26.16 (95%)
Games | N: 448 W: 209 L: 64 D: 175
```
```
ELO   | 95.09 +- 20.99 (95%)
LLR   | 3.12 (-2.94, 2.94) [0.00, 5.00]
Games | N: 528 W: 200 L: 59 D: 269
```
=> Allow null pruning at all depths

Halogen/src/Move.cpp, Halogen/src/Move.h, Halogen/src/Search.cpp, Halogen/src/TTEntry.cpp, Halogen/src/TTEntry.h, Halogen/src/TranspositionTable.cpp, Halogen/src/TranspositionTable.h
```
ELO   | 15.04 +- 8.06 (95%)
Games | N: 3652 W: 1013 L: 855 D: 1784
```
```
ELO   | 3.91 +- 3.14 (95%)
Games | N: 24816 W: 6700 L: 6421 D: 11695
```
=> Improved scaling

Halogen/src/Search.cpp
```
ELO   | 32.04 +- 12.47 (95%)
Games | N: 1664 W: 538 L: 385 D: 741
```
```
ELO   | 21.90 +- 9.40 (95%)
Games | N: 2256 W: 556 L: 414 D: 1286
```
=> Bench: 1449984

Halogen/src/BitBoardDefine.cpp, Halogen/src/Network.cpp, Halogen/src/Network.h, Halogen/src/Position.cpp, Halogen/src/TTEntry.h
Bench: 16572416
```
ELO   | -10.83 +- 6.62 (95%)
LLR   | -3.03 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 5616 W: 1405 L: 1580 D: 2631
```
This patch has a significant regression of performance, but is necessary due to the severe nature of the bugs that it fixes.
=> Fix instances of undefined behaviour

Halogen/src/Search.cpp
```
ELO   | 5.83 +- 4.42 (95%)
Games | N: 12400 W: 3348 L: 3140 D: 5912
```
```
ELO   | 4.51 +- 3.49 (95%)
Games | N: 15872 W: 3420 L: 3214 D: 9238
```
=> Allow futility pruning at all depths

Halogen/src/Search.cpp
```
ELO   | 4.80 +- 5.81 (95%)
Games | N: 7168 W: 1925 L: 1826 D: 3417
```
```
ELO   | 4.68 +- 3.55 (95%)
Games | N: 14848 W: 3099 L: 2899 D: 8850
```
=> Restrict the depth that futility pruning is applied to

Halogen/src/Search.cpp
```
ELO   | 1.60 +- 4.19 (95%)
Games | N: 13664 W: 3573 L: 3510 D: 6581
```
=> Verify null move pruning when being checkmated

Halogen/src/TimeManage.cpp
```
ELO   | -0.71 +- 2.42 (95%)
Games | N: 40384 W: 10299 L: 10382 D: 19703
```
=> Use all available time when given the command go movetime

Halogen/src/Network.cpp, Halogen/src/Position.cpp
```
ELO   | 4.30 +- 3.41 (95%)
Games | N: 19008 W: 4655 L: 4420 D: 9933
```
Rounding costs time and gives accuracy that we don't need
=> Bench: 12103680

Halogen/src/EvalCache.cpp, Halogen/src/EvalCache.h
```
ELO   | 3.04 +- 4.73 (95%)
Games | N: 9728 W: 2334 L: 2249 D: 5145
```
=> Refactor eval cache and improve speed

Halogen/src/Search.cpp
```
ELO   | 12.77 +- 6.64 (95%)
Games | N: 3920 W: 804 L: 660 D: 2456
```
```
ELO   | 2.69 +- 2.07 (95%)
Games | N: 47136 W: 10501 L: 10136 D: 26499
```
=> Limit futility pruning to a max depth of 10

Halogen/src/Search.cpp, Halogen/src/Search.h
```
ELO   | -1.62 +- 3.97 (95%)
LLR   | 3.01 (-2.94, 2.94) [-10.00, 0.00]
Games | N: 12880 W: 2795 L: 2855 D: 7230
```
=> Output aspiration fail

Halogen/src/TTEntry.cpp, Halogen/src/TTEntry.h, Halogen/src/TranspositionTable.cpp, Halogen/src/TranspositionTable.h
```
ELO   | 2.04 +- 4.25 (95%)
Games | N: 12256 W: 2972 L: 2900 D: 6384
```
```
ELO   | 10.15 +- 6.17 (95%)
Games | N: 5476 W: 1313 L: 1153 D: 3010
```
=> Use a better transposition replacement scheme

Halogen/src/Search.cpp
```
ELO   | 4.87 +- 3.80 (95%)
Games | N: 15488 W: 3847 L: 3630 D: 8011
```
```
ELO   | 6.70 +- 4.51 (95%)
Games | N: 8656 W: 1732 L: 1565 D: 5359
```
=> Implement reverse futility pruning

Halogen/src/Network.cpp, Halogen/src/Network.h, Halogen/src/Position.h
No crashes after 15k LTC games.
```
ELO   | -0.27 +- 3.34 (95%)
LLR   | -1.86 (-2.94, 2.94) [0.00, 5.00]
Games | N: 15408 W: 2866 L: 2878 D: 9664
```
Tested for regression
```
ELO   | -2.19 +- 3.61 (95%)
LLR   | 3.01 (-2.94, 2.94) [-10.00, 0.00]
Games | N: 16784 W: 3919 L: 4025 D: 8840
```
=> Fix source of rare crashes

Halogen/src/Position.h, Halogen/src/Search.cpp
```
ELO   | -3.01 +- 2.36 (95%)
LLR   | -2.96 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 39872 W: 9421 L: 9766 D: 20685
```
=> Tweak output

Halogen/src/TimeManage.cpp
This patch fixes a oversight that the nodes value passed to the function from `position.GetNodes()` does not count upward, but counts chunks up to a maximum of 4096 before resetting at zero. As such, the condition to check every node in the first 1024 causes the engine to check the remaining time for 1/4 of nodes rather than 1/1024 nodes as intended. 
```
ELO   | 33.81 +- 12.37 (95%)
LLR   | 3.04 (-2.94, 2.94) [0.00, 5.00]
Games | N: 1536 W: 462 L: 313 D: 761
```
Bench: 13438976
=> Time check fix

Halogen/src/Search.cpp
This patch fixes the blunder that Halogen played in this TCEC game (https://tcec-chess.com/#div=ql&game=5&season=20) which took a game which should have been drawn and caused Halogen to lose. When in a position with only king moves and pawn moves, it is too risky to allow null move pruning. The previous condition allowed null move pruning if at least one side had non king/pawn material.
```
ELO   | -0.06 +- 2.43 (95%)
Games | N: 30080 W: 5760 L: 5765 D: 18555
```
=> Fix NMP late game condition to be more restrictive

Halogen/src/Search.cpp, Halogen/src/Search.h, Halogen/src/main.cpp
No strength change. Exposes more parameters to the UCI.
```
ELO   | -0.42 +- 5.36 (95%)
LLR   | 2.99 (-2.94, 2.94) [-10.00, 0.00]
Games | N: 7472 W: 1732 L: 1741 D: 3999
```
=> Allow more search parameters to be tuneable

Halogen/src/Search.cpp, Halogen/src/Search.h, Halogen/src/main.cpp
The reduction formula for null move pruning has been adjusted and tuned with chess tuning tools. The new formula is  
`reduction = 4 + depth / 6 + min(3, (staticScore - beta) / 250);`
```
ELO   | 7.34 +- 5.02 (95%)
Games | N: 8288 W: 1957 L: 1782 D: 4549
```
```
ELO   | 10.90 +- 5.90 (95%)
LLR   | 3.02 (-2.94, 2.94) [0.00, 5.00]
Games | N: 4688 W: 900 L: 753 D: 3035
```
=> Tune the null move pruning reduction scheme

Halogen/src/Search.cpp
When the depth remaining is at least 10, verify the null move pruning in order to fix zugzwang blindness.
```
ELO   | 1.94 +- 4.03 (95%)
Games | N: 12736 W: 2890 L: 2819 D: 7027
```
```
ELO   | -0.49 +- 2.64 (95%)
LLR   | -2.97 (-2.94, 2.94) [0.00, 5.00]
Games | N: 22672 W: 3850 L: 3882 D: 14940
```
Testing shows no strength change, but Halogen will analyse much better in zugzwang positions.
=> Add null move verification for high depth searches

Halogen/src/EvalNet.cpp, Halogen/src/EvalNet.h
Non functional change.
```
ELO   | -0.86 +- 4.80 (95%)
LLR   | 3.00 (-2.94, 2.94) [-10.00, 0.00]
Games | N: 8928 W: 1976 L: 1998 D: 4954
```
=> Small refactor

Halogen/src/Position.cpp, Halogen/src/Position.h, Halogen/src/Search.cpp, Halogen/src/Search.h
```
ELO   | 6.04 +- 5.87 (95%)
Games | N: 5984 W: 1385 L: 1281 D: 3318
```
```
ELO   | -9.11 +- 5.65 (95%)
LLR   | -2.95 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 6030 W: 1175 L: 1333 D: 3522
```
This patch finally allows Halogen to again count TB hits and nodes correctly, and not in multiplies of 4096. Small regression with SMP but possible elo gain for single threaded so I'm accepting this patch and assuming I'll find SMP improvements in future.
=> Remove node batches

Halogen/Halogen/Halogen.vcxproj, Halogen/Halogen/Halogen.vcxproj.filters, Halogen/src/BitBoardDefine.h, Halogen/src/Position.h, Halogen/src/Search.cpp, Halogen/src/Search.h, Halogen/src/SearchData.cpp, Halogen/src/SearchData.h, Halogen/src/TimeManage.cpp, Halogen/src/TimeManage.h, Halogen/src/main.cpp
```
ELO   | -1.41 +- 1.23 (95%)
Games | N: 137904 W: 30653 L: 31211 D: 76040
```
Fairly major refactor. Search limits can now work with any and all of the following
- time based limits
- mate searches
- depth limited searches
=> Search limits

Halogen/src/MoveGeneration.cpp
```
ELO   | 7.69 +- 6.54 (95%)
Games | N: 4928 W: 1176 L: 1067 D: 2685
```
```
ELO   | -1.50 +- 3.78 (95%)
LLR   | -2.99 (-2.94, 2.94) [0.00, 5.00]
Games | N: 14352 W: 3153 L: 3215 D: 7984
```
This patch fixes a bug where legal castling moves might incorrectly be flagged as illegal. This would cause a hash move which is a castling move. Patch doesn't gain elo, but does pass simplification bounds.
=> Fix bug in MoveIsLegal function

Halogen/src/Search.cpp, Halogen/src/Search.h, Halogen/src/TimeManage.h, Halogen/src/main.cpp
```
ELO   | 3.46 +- 4.86 (95%)
Games | N: 8848 W: 2043 L: 1955 D: 4850
```
=> Fix undefined behaviour

Halogen/src/Search.cpp
```
ELO   | 5.24 +- 4.03 (95%)
Games | N: 9888 W: 1787 L: 1638 D: 6463
```
```
ELO   | 6.05 +- 4.64 (95%)
LLR   | 3.07 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 9472 W: 2171 L: 2006 D: 5295
```
Extend static null move pruning to depth <= 2
=> Extend SNMP

Halogen/src/Search.cpp
```
ELO   | 5.24 +- 4.03 (95%)
Games | N: 9888 W: 1787 L: 1638 D: 6463
```
```
ELO   | 6.05 +- 4.64 (95%)
LLR   | 3.07 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 9472 W: 2171 L: 2006 D: 5295
```
=> Extend SNMP to depth 2

Halogen/src/Search.cpp
```
ELO   | 2.89 +- 2.75 (95%)
Games | N: 21418 W: 3834 L: 3656 D: 13928
```
```
ELO   | 4.96 +- 4.18 (95%)
LLR   | 3.02 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 12112 W: 2863 L: 2690 D: 6559
```
=> Apply LMR when when in check, giving check, or the end game

Halogen/src/Search.cpp, Halogen/src/Search.h, Halogen/src/main.cpp
```
ELO   | 8.13 +- 5.19 (95%)
LLR   | 2.98 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 5984 W: 1112 L: 972 D: 3900
```
```
ELO   | 6.11 +- 4.73 (95%)
LLR   | 2.99 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 9104 W: 2082 L: 1922 D: 5100
```
=> Tune static null move pruning

Halogen/Halogen/Halogen.vcxproj, Halogen/Halogen/Halogen.vcxproj.filters, Halogen/src/MoveGenerator.cpp, Halogen/src/MoveGenerator.h, Halogen/src/Search.cpp, Halogen/src/Search.h
Generate the Hash move first, before attempting to generate the other moves
```
ELO   | 13.26 +- 7.09 (95%)
LLR   | 3.03 (-2.94, 2.94) [0.00, 5.00]
Games | N: 4064 W: 973 L: 818 D: 2273
```
=> Bench: 26358524

Halogen/src/Search.cpp
```
ELO   | 4.61 +- 3.98 (95%)
Games | N: 12736 W: 2862 L: 2693 D: 7181
```
=> No checkmate detection in quiescence search

Halogen/src/MoveGenerator.cpp
```
ELO   | 1.54 +- 1.51 (95%)
LLR   | 2.95 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 89440 W: 19829 L: 19433 D: 50178
```
=> Skip TT move in quiescence search

Halogen/src/Search.cpp
```
ELO   | 5.22 +- 4.00 (95%)
LLR   | 2.95 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 9792 W: 1733 L: 1586 D: 6473
```
```
ELO   | 3.44 +- 3.28 (95%)
LLR   | 2.97 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 19184 W: 4372 L: 4182 D: 10630
```
=> Lower LMR reduction in PV nodes

Halogen/src/BitBoardDefine.cpp, Halogen/src/BitBoardDefine.h, Halogen/src/MoveGeneration.cpp
```
ELO   | -2.27 +- 2.34 (95%)
LLR   | -2.97 (-2.94, 2.94) [-4.00, 1.00]
Games | N: 37216 W: 8102 L: 8345 D: 20769
```
Small regression permitted
=> Simplify pawn attack code

Halogen/src/MoveGenerator.cpp, Halogen/src/MoveGenerator.h, Halogen/src/Search.cpp, Halogen/src/SearchData.cpp, Halogen/src/SearchData.h
```
ELO   | 19.02 +- 9.00 (95%)
Games | N: 2560 W: 643 L: 503 D: 1414
```
```
ELO   | 36.04 +- 11.75 (95%)
LLR   | 2.97 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 1248 W: 297 L: 168 D: 783
```
=> Use Ethereal style history adjustment

Halogen/src/MoveGenerator.cpp
```
ELO   | 4.58 +- 5.38 (95%)
Games | N: 7280 W: 1708 L: 1612 D: 3960
```
=> Fix potential crash in history update

Halogen/Halogen/Halogen.vcxproj, Halogen/src/BitBoardDefine.cpp, Halogen/src/BitBoardDefine.h, Halogen/src/Makefile, Halogen/src/MoveGeneration.cpp, Halogen/src/TranspositionTable.cpp
```
ELO   | 7.98 +- 5.54 (95%)
LLR   | 3.01 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 6752 W: 1592 L: 1437 D: 3723
```
A decent speedup and a reduction in lines of code
=> Use constexpr functions to initialize bit board arrays

Halogen/src/main.cpp
```
ELO   | 15.42 +- 7.05 (95%)
LLR   | 3.03 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 2976 W: 542 L: 410 D: 2024
```
```
ELO   | 4.61 +- 3.97 (95%)
LLR   | 2.99 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 12880 W: 2914 L: 2743 D: 7223
```
As the number of moves increases, use a higher proportion of remaining time so that it actually gets used up at some point during the game.
=> Bench: 25784886

Halogen/src/BitBoardDefine.h, Halogen/src/Search.cpp, Halogen/src/main.cpp
```
ELO   | -0.06 +- 2.71 (95%)
Games | N: 27648 W: 6048 L: 6053 D: 15547
```
```
Score of Halogen vs Halogen_master: 163 - 168 - 617 [0.497]
...      Halogen playing White: 108 - 53 - 313  [0.558] 474
...      Halogen playing Black: 55 - 115 - 304  [0.437] 474
...      White vs Black: 223 - 108 - 617  [0.561] 948
Elo difference: -1.8 +/- 13.1, LOS: 39.2 %, DrawRatio: 65.1 %
954 of 10000 games finished.
```
=> Fix usage of EGTB at root

Halogen/src/Search.cpp
```
ELO   | -9.43 +- 7.04 (95%)
LLR   | -2.99 (-2.94, 2.94) [-10.00, 0.00]
Games | N: 3428 W: 582 L: 675 D: 2171
```
It's potentially unsound, I have no way of testing at very high core counts, and removing this will allow for elo gains elsewhere, for example early abort when a thread fails low or high.
=> Remove SMP aspiration scheme for an elo loss

Halogen/src/Search.cpp
```
ELO   | -0.84 +- 1.93 (95%)
Games | N: 53664 W: 11538 L: 11667 D: 30459
```
```
ELO   | 3.06 +- 4.57 (95%)
LLR   | 2.94 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 9536 W: 2092 L: 2008 D: 5436
```
=> Limit history depth to 20

Halogen/src/Search.cpp, Halogen/src/Search.h, Halogen/src/SearchData.cpp, Halogen/src/SearchData.h, Halogen/src/main.cpp
```
ELO   | -1.71 +- 1.96 (95%)
LLR   | -0.04 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 52144 W: 11148 L: 11404 D: 29592
```
```
ELO   | 11.14 +- 6.99 (95%)
Games | N: 3462 W: 688 L: 577 D: 2197
```
=> Added multi-pv mode

Halogen/src/SearchData.cpp
```
ELO   | -1.85 +- 1.97 (95%)
LLR   | -0.54 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 51184 W: 10831 L: 11103 D: 29250
```
=> Fix best move selection in multiPV mode

Halogen/src/MoveGenerator.h
The greater than overload was never actually used, but this error should definitely be fixed. Thanks to @thehlopster for pointing this out to me.
=> Correctly overload 'greater than' operator for ExtendedMove objects

Halogen/src/MoveGeneration.cpp
When inserting a temporary object into a container using the methods `push_back`, the object is constructed outside the container and then moved/copied into the container. On the other hand, the `emplace_back` methods allow you to eliminate the extra call of the move/copy constructor and create the object "in place" inside the container instead, perfectly passing the function's parameters to the constructor.
=> [fix] decreased performance

Halogen/src/Search.cpp
```
ELO   | 1.35 +- 1.30 (95%)
LLR   | 0.32 (-2.94, 2.94) [0.00, 5.00]
Games | N: 83056 W: 12830 L: 12508 D: 57718
```
```
ELO   | 2.97 +- 2.38 (95%)
Games | N: 34256 W: 7315 L: 7022 D: 19919
```
=> Use FIFO system for Killer moves

Halogen/src/main.cpp
```
ELO   | 3.64 +- 2.79 (95%)
Games | N: 17754 W: 2744 L: 2558 D: 12452
```
```
ELO   | 25.30 +- 10.18 (95%)
Games | N: 1912 W: 478 L: 339 D: 1095
```
=> Adjust time usage to be less aggressive

Halogen/src/MoveGeneration.cpp
```
ELO   | 3.40 +- 2.70 (95%)
LLR   | 3.02 (-2.94, 2.94) [0.00, 5.00]
Games | N: 26096 W: 5504 L: 5249 D: 15343
```
This patch previously failed, but after https://github.com/KierenP/Halogen/pull/269 the Move class now can use move semantics which likely helps?
=> Use emplace_back

Halogen/src/Search.cpp, Halogen/src/Search.h, Halogen/src/SearchData.cpp, Halogen/src/main.cpp
```
ELO   | -0.69 +- 1.99 (95%)
Games | N: 48020 W: 9849 L: 9944 D: 28227
```
=> Fix MultiPV when the number of legal moves is lower

Halogen/src/BitBoardDefine.h, Halogen/src/EvalNet.cpp, Halogen/src/EvalNet.h, Halogen/src/Network.cpp, Halogen/src/Network.h, Halogen/src/main.cpp, HalogenTests/TestEvalNet.cpp
```
ELO   | 0.08 +- 2.59 (95%)
LLR   | 3.03 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 27354 W: 5446 L: 5440 D: 16468
```
=> Scale the network during initialization

Halogen/src/Search.cpp, Halogen/src/main.cpp
```
ELO   | 6.37 +- 4.12 (95%)
Games | N: 8232 W: 1318 L: 1167 D: 5747
```
```
ELO   | 3.80 +- 3.02 (95%)
Games | N: 20304 W: 4178 L: 3956 D: 12170
```
=> Extend all checks

Halogen/src/Search.cpp, Halogen/src/SearchData.h, Halogen/src/main.cpp
Based on https://github.com/Luecx/Koivisto/commit/c8f01211c290a582b69e4299400b667a7731a9f7
The idea of draw randomization originated in Stockfish. The implementation is very similar, but the idea behind this patch is based on a different idea, namely the Beal effect. While the idea is based on The Beal effect, it is important to keep in mind that only limited testing has been done and the real reason behind the elo gain is still open to interpretation. It is also important to note that this is the first version tried in Koivisto, so tuning/tweaks are likely possible.  Variations on the range (currently a range of 16 score grain) need to be tested. 
Elo tests in Halogen:
http://chess.grantnet.us/test/10830/
ELO   | 6.20 +- 4.40 (95%)
LLR   | 2.97 …
=> Randomize draw scores

Halogen/src/BitBoardDefine.h, Halogen/src/EvalNet.cpp, Halogen/src/Search.cpp, Halogen/src/SearchData.h, Halogen/src/TTEntry.cpp, Halogen/src/TranspositionTable.cpp, Halogen/src/main.cpp
Without Syzygy:
```
ELO   | 0.21 +- 2.77 (95%)
Games | N: 24520 W: 4987 L: 4972 D: 14561
```
With Syzygy:
```
ELO   | 1.78 +- 3.74 (95%)
Games | N: 13272 W: 2693 L: 2625 D: 7954
```
=> Adjust EGTB scores when storing in transposition table

Halogen/src/MoveGenerator.cpp, Halogen/src/MoveGenerator.h, Halogen/src/Search.cpp, Halogen/src/main.cpp
```
ELO   | 13.87 +- 6.49 (95%)
Games | N: 3384 W: 590 L: 455 D: 2339
```
```
ELO   | 5.47 +- 4.01 (95%)
Games | N: 11696 W: 2471 L: 2287 D: 6938
```
=> Add late move pruning

Halogen/src/Search.cpp, Halogen/src/main.cpp
```
ELO   | 5.41 +- 5.38 (95%)
Games | N: 6488 W: 1369 L: 1268 D: 3851
```
=> Ignore negative depth for futility pruning and late move pruning

Halogen/src/BitBoardDefine.h, Halogen/src/SearchData.cpp
```
ELO   | 1.55 +- 3.66 (95%)
Games | N: 14088 W: 2909 L: 2846 D: 8333
```
=> Expand the maximum range for evaluation scores

Halogen/src/MoveGenerator.cpp, Halogen/src/MoveGenerator.h, Halogen/src/MoveList.h, Halogen/src/Search.cpp, Halogen/src/SearchData.h
```
ELO   | -2.69 +- 2.11 (95%)
LLR   | -2.99 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 41232 W: 8058 L: 8377 D: 24797
```
This loses elo but is necessary to allow singular extensions and bugs in the future.
=> Implement a move list pool

Halogen/src/Move.cpp, Halogen/src/Move.h, Halogen/src/MoveGeneration.cpp, Halogen/src/MoveGenerator.cpp, Halogen/src/MoveGenerator.h, Halogen/src/MoveList.cpp, Halogen/src/MoveList.h, Halogen/src/Position.cpp, Halogen/src/Search.cpp, Halogen/src/Search.h, Halogen/src/SearchData.h, Halogen/src/TTEntry.cpp, Halogen/src/main.cpp
```
ELO   | 1.10 +- 3.37 (95%)
Games | N: 16488 W: 3355 L: 3303 D: 9830
```
Doing this makes allocating a MoveList very cheap and means we can remove constructs like the MoveListPool as recycling the objects is no longer necessary. Watch out for UB though as MoveList needs .reset() to be called before it can be used!
=> Make the Move class trivial

Halogen/src/Position.cpp, Halogen/src/main.cpp, HalogenTests/TestMoveGeneration.cpp
```
ELO   | 3.25 +- 3.81 (95%)
Games | N: 9312 W: 1407 L: 1320 D: 6585
```
```
ELO   | 5.66 +- 5.47 (95%)
Games | N: 6136 W: 1266 L: 1166 D: 3704
```
```
ELO   | 4.77 +- 3.61 (95%)
Games | N: 13992 W: 2861 L: 2669 D: 8462
```
=> Correct interaction between 3 fold rep and ep passant squares

Halogen/src/Position.h, Halogen/src/Search.cpp, Halogen/src/SearchData.cpp, Halogen/src/SearchData.h, Halogen/src/main.cpp
```
ELO   | -0.52 +- 2.05 (95%)
Games | N: 42544 W: 8231 L: 8295 D: 26018
```
```
ELO   | -1.12 +- 1.75 (95%)
LLR   | 0.48 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 45258 W: 6694 L: 6840 D: 31724
```
=> Simplify program control flow with exceptions

Halogen/src/Network.cpp, Halogen/src/main.cpp
New network was trained using ~1.7 billion positions generated from depth 9 Ethereal 13.00 (NNUE) selfplay games with passive adjudication settings and wildly unbalanced openings. For each position, an evaluation (CP Score) and result (Win/Loss/Draw) was used as the cost function, with equal balance between the two.
After 60 epochs using LR=0.001 with an Adam optimizer, the LR was dropped to 0.0001 for an additional two epochs before concluding training. It remains to be seen whether additional epochs would gain elo, or if further LR drops would be of benefit.
ELO   | 85.95 +- 4.76 (95%)
LLR   | 0.00 (-2.94, 2.94) [0.00, 0.00]
Games | N: 10476 W: 3943 L: 1403 D: 5130
http://chess.grantnet.us/test/11707/
ELO   | 81.95 +- 7.68 (95%)
SPRT  | 40.0+0.40s …
=> Update default Neural Network [b8a1b7d5.nn] (768x512x1)

Halogen/src/EvalNet.cpp, Halogen/src/main.cpp, HalogenTests/TestEvalNet.cpp
```
ELO   | 3.42 +- 3.63 (95%)
LLR   | 3.03 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 9240 W: 1260 L: 1169 D: 6811
```
```
ELO   | 0.61 +- 2.83 (95%)
Games | N: 20904 W: 3792 L: 3755 D: 13357
```
=> Remove score adjustment when winning side has no pawns

src/MoveGenerator.h, src/Search.cpp, src/main.cpp
```
ELO   | 3.70 +- 2.80 (95%)
Games | N: 16792 W: 2476 L: 2297 D: 12019
```
```
ELO   | 4.88 +- 3.63 (95%)
Games | N: 13088 W: 2536 L: 2352 D: 8200
```
=> Implement new futility pruning scheme

src/Search.cpp, src/SearchData.cpp, src/SearchData.h, src/main.cpp
Update current best move on fail-high aspiration searches 
LTC 
http://chess.grantnet.us/test/12665/
```
ELO   | 15.78 +- 6.85 (95%)
GAMES | N: 2864 W: 481 L: 351 D: 2032
```
STC 
http://chess.grantnet.us/test/12663/
```
ELO   | 12.96 +- 6.65 (95%)
LLR   | 3.05 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 3968 W: 826 L: 678 D: 2464
```
=> Update best move on fail high

src/MoveGenerator.cpp
```
ELO   | 3.14 +- 2.79 (95%)
GAMES | N: 17584 W: 2675 L: 2516 D: 12393
```
```
ELO   | 2.47 +- 1.91 (95%)
GAMES | N: 48920 W: 9633 L: 9285 D: 30002
```
=> Fix MoveGenerator to allow killer moves when in check

src/MoveGenerator.cpp, src/MoveGenerator.h
```
ELO   | 0.05 +- 2.53 (95%)
GAMES | N: 27680 W: 5298 L: 5294 D: 17088
```
=> Separate loud moves from quiet moves in MoveGenerator

src/MoveGenerator.cpp, src/SearchData.cpp, src/SearchData.h, src/main.cpp
```
ELO   | 0.01 +- 2.49 (95%)
GAMES | N: 28528 W: 5469 L: 5468 D: 17591
```
=> Further adjust history table code to allow for CMH

src/Position.cpp, src/main.cpp
```
ELO   | 6.82 +- 5.82 (95%)
GAMES | N: 5352 W: 1102 L: 997 D: 3253
```
=> Bugfix: Move stack was not reset between UCI commands

src/MoveGenerator.cpp, src/SearchData.cpp, src/SearchData.h, src/main.cpp
```
ELO   | 5.38 +- 3.66 (95%)
GAMES | N: 10072 W: 1544 L: 1388 D: 7140
```
```
ELO   | 0.54 +- 2.00 (95%)
LLR   | -2.95 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 44288 W: 8486 L: 8417 D: 27385
```
=> Add counter move history

src/TTEntry.cpp, src/TTEntry.h, src/TranspositionTable.cpp, src/TranspositionTable.h, src/main.cpp
```
ELO   | 5.89 +- 4.79 (95%)
GAMES | N: 5840 W: 896 L: 797 D: 4147
```
```
ELO   | 9.69 +- 6.68 (95%)
GAMES | N: 3944 W: 806 L: 696 D: 2442
```
=> Improve allocation speed for transposition table

src/TranspositionTable.cpp, src/TranspositionTable.h
```
ELO   | 0.05 +- 2.54 (95%)
GAMES | N: 27632 W: 5312 L: 5308 D: 17012
```
=> Remove class FastAllocateVector

src/MoveGeneration.cpp, src/MoveList.h, src/Search.cpp, src/SearchData.cpp, src/SearchData.h, src/main.cpp
```
ELO   | 5.13 +- 5.16 (95%)
GAMES | N: 6632 W: 1314 L: 1216 D: 4102
```
=> Use a more efficient memory layout for PV tables

src/SearchData.cpp, src/main.cpp
```
ELO   | 1.47 +- 3.49 (95%)
GAMES | N: 14680 W: 2867 L: 2805 D: 9008
```
No effect on playing strength, but this is important for using the engine with a GUI for analysis.
=> Flush info string output

src/MoveGeneration.cpp, src/main.cpp
```
ELO   | 10.82 +- 6.12 (95%)
GAMES | N: 4784 W: 1000 L: 851 D: 2933
```
```
10.20.7.exe   |   10.20.6.exe    |
mu        |        mu        |     SE      DF      t         p     speedup (%)
------------------+------------------|
3565000.000|       3478000.000|
3564500.000|       3477500.000|  707.107    2  123.036580  0.000066   2.470889
3561000.000|       3477000.000|  3559.026   4   23.601962  0.000019   2.387042
3551000.000|       3474000.000| 10739.336   6   7.169903   0.000372   2.192171
3553400.000|       3474400.000|  8667.179   8   9.114845   0.000017   2.248214
3553500.000|       3474000.000|  7088.723   10  11.214995  0.000001   2.262540
3554857.143|       3473714.286|  6149.498   12  13.195037 …
```
=> Template move generation code on the side to move

src/Search.cpp, src/Search.h, src/SearchData.cpp, src/SearchData.h, src/TimeManage.cpp, src/TimeManage.h, src/main.cpp
```
ELO   | 5.15 +- 3.54 (95%)
GAMES | N: 10664 W: 1617 L: 1459 D: 7588
```
```
ELO   | 9.60 +- 5.71 (95%)
GAMES | N: 5648 W: 1202 L: 1046 D: 3400
```
```
ELO   | 6.67 +- 4.25 (95%)
GAMES | N: 7816 W: 1266 L: 1116 D: 5434
```
=> Preserve history tables between searches

src/Search.cpp, src/SearchData.cpp, src/SearchData.h, src/SearchLimits.cpp, src/SearchLimits.h, src/main.cpp
```
ELO   | -0.12 +- 2.26 (95%)
GAMES | N: 32232 W: 5735 L: 5746 D: 20751
```
=> Refactor search limit handling

src/TranspositionTable.cpp, src/main.cpp
```
ELO   | 0.36 +- 4.90 (95%)
LLR   | 3.02 (-2.94, 2.94) [-10.00, 0.00]
GAMES | N: 6792 W: 1201 L: 1194 D: 4397
```
=> Correctly calculate TT table pressure

src/Search.cpp, src/SearchData.cpp, src/SearchData.h, src/StagedMoveGenerator.cpp, src/main.cpp
```
ELO   | 0.45 +- 2.65 (95%)
GAMES | N: 22920 W: 4006 L: 3976 D: 14938
```
=> Simplify the code for history tables

src/MoveGeneration.cpp, src/main.cpp
```
ELO   | 4.17 +- 12.84 (95%)
GAMES | N: 1000 W: 184 L: 172 D: 644
```
Tested for non-regression.
Baseline perft: `63768194 nps`
Current perft: `65712350 nps`
Change: `+3.05%`
=> Improve pinned piece detection

src/MoveGeneration.cpp, src/main.cpp
Tested for non-regression:
```
ELO   | 8.96 +- 12.56 (95%)
GAMES | N: 1008 W: 186 L: 160 D: 662
```
Bench speed comparison:
```
dev       |      master      |
mu        |        mu        |     SE      DF      t         p     speedup (%) 
------------------+------------------|
3281000.000|       3175000.000|
3296500.000|       3187500.000| 19912.308   2   5.474001   0.031790   3.362122  
3300000.000|       3190000.000| 12274.635   4   8.961570   0.000858   3.389831  
3306000.000|       3188750.000| 10625.245   6   11.035040  0.000033   3.610609  
3304400.000|       3180200.000| 11974.974   8   10.371630  0.000006   3.830614  
3299166.667|       3181333.333| 11147.745   10  10.570150  0.000001   3.636551  
3298285.714|       3178285.714|  9941.324   12 …
```
=> Use the in-check move generators in regular search

src/Network.cpp, src/Network.h, src/main.cpp
```
Elo   | 1.63 +- 4.23 (95%)
Games | N: 13406 W: 3505 L: 3442 D: 6459
Penta | [165, 1542, 3244, 1569, 183]
```
=> Align network weights/bias/accumulators to 32 bytes for better AVX2 support

src/Makefile, src/MoveGeneration.cpp, src/Score.h, src/Search.cpp, src/Search.h, src/SearchData.cpp, src/SearchData.h, src/main.cpp
```
Elo   | 5.21 +- 6.18 (95%)
Games | N: 6202 W: 1636 L: 1543 D: 3023
Penta | [66, 691, 1512, 748, 84]
http://chess.grantnet.us/test/36183/
```
=> Rewrite search control flow to avoid exceptions

src/SearchLimits.cpp, src/SearchLimits.h, src/TimeManage.cpp, src/TimeManage.h, src/main.cpp
```
Elo   | 5.82 +- 5.02 (95%)
Games | N: 9492 W: 2532 L: 2373 D: 4587
Penta | [109, 1038, 2297, 1189, 113]
http://chess.grantnet.us/test/36202/
```
```
Elo   | 7.41 +- 5.78 (95%)
SPRT  | 8.0+0.00s Threads=1 Hash=8MB
Games | N: 7410 W: 2064 L: 1906 D: 3440
Penta | [114, 804, 1740, 904, 143]
http://chess.grantnet.us/test/36203/
```
```
Elo   | 10.22 +- 7.13 (95%)
SPRT  | 40/8.0+0.00s Threads=1 Hash=8MB
Games | N: 4592 W: 1225 L: 1090 D: 2277
Penta | [45, 463, 1153, 582, 53]
http://chess.grantnet.us/test/36204/
```
=> Adjust time controls to more smoothly apply the buffer time

src/Search.cpp, src/Search.h, src/StagedMoveGenerator.h, src/main.cpp
```
Elo   | -2.47 +- 3.12 (95%)
LLR   | -1.67 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 23810 W: 5871 L: 6040 D: 11899
Penta | [334, 2912, 5528, 2851, 280]
http://chess.grantnet.us/test/36288/
```
=> Avoid duplicate search on Killer move when it is also the TT move

src/Search.cpp, src/Search.h, src/StagedMoveGenerator.cpp, src/main.cpp
Removing the killer workaround causes elo loss due to interactions with LMR. After tuning LMR with a new scheme the patch overall gains elo.
```
Elo   | 4.19 +- 3.93 (95%)
Games | N: 13668 W: 3199 L: 3034 D: 7435
Penta | [92, 1566, 3360, 1717, 99]
http://chess.grantnet.us/test/36304/
```
```
Elo   | 4.51 +- 4.07 (95%)
Games | N: 13868 W: 3527 L: 3347 D: 6994
Penta | [156, 1646, 3201, 1724, 207]
http://chess.grantnet.us/test/36302/
```
=> Remove Killer move workaround, tune LMR scheme as a linear regression with interaction factor

src/Search.cpp, src/SearchData.h, src/StagedMoveGenerator.cpp, src/main.cpp
```
Elo   | 12.70 +- 7.72 (95%)
Games | N: 3422 W: 816 L: 691 D: 1915
Penta | [20, 357, 830, 486, 18]
http://chess.grantnet.us/test/36314/
```
```
Elo   | 4.59 +- 4.05 (95%)
Games | N: 13616 W: 3370 L: 3190 D: 7056
Penta | [184, 1560, 3130, 1760, 174]
http://chess.grantnet.us/test/36312/
```
=> Add singular extensions

src/TimeManage.cpp, src/main.cpp
```
$ ./cutechess-ob -repeat -recover -variant standard -concurrency 20 -games 1280 -engine dir=Engines/ cmd=./Halogen-time-fix.exe proto=uci tc=0.001+1 option.Threads=1 option.Hash=8 name=Halogen-time-fix -engine dir=Engines/ cmd=./Halogen-no-fix.exe proto=uci tc=0.001+1 option.Threads=1 option.Hash=8 name=Halogen-no-fix -openings file=Books/UHO_4060_v2.epd format=epd order=random start=1 -srand 36525 -pgnout PGNs/time_test.pgn
Finished game 170 (Halogen-no-fix vs Halogen-time-fix): 0-1 {White loses on time}
Score of Halogen-time-fix vs Halogen-no-fix: 68 - 27 - 56  [0.636] 151
```
At high increment time controls soft_limit_ may be much greater than hard_limit_, and the logic to abort the search may result in a time-loss. This fix appears to lose ELO at STC, but I suspect this is simply …
=> Fix time loss bug

src/Search.cpp, src/SearchData.h, src/main.cpp
```
Elo   | 4.11 +- 3.87 (95%)
Games | N: 13534 W: 3047 L: 2887 D: 7600
Penta | [60, 1551, 3397, 1687, 72]
http://chess.grantnet.us/test/36531/
```
```
Elo   | 3.52 +- 3.35 (95%)
Games | N: 19348 W: 4627 L: 4431 D: 10290
Penta | [185, 2263, 4616, 2391, 219]
http://chess.grantnet.us/test/36491/
```
=> Add double singular extensions

src/Search.cpp, src/main.cpp
```
Elo   | 3.62 +- 3.54 (95%)
Games | N: 16612 W: 3835 L: 3662 D: 9115
Penta | [98, 1875, 4199, 2024, 110]
http://chess.grantnet.us/test/36545/
```
```
Elo   | 3.27 +- 3.12 (95%)
Games | N: 22008 W: 5210 L: 5003 D: 11795
Penta | [205, 2553, 5309, 2704, 233]
http://chess.grantnet.us/test/36494/
```
=> Add Multi-Cut pruning

src/TranspositionTable.cpp, src/main.cpp
```
Elo   | 3.77 +- 3.51 (95%)
LLR   | 3.02 (-2.94, 2.94) [0.00, 5.00]
Games | N: 18456 W: 4628 L: 4428 D: 9400
Penta | [200, 2204, 4260, 2324, 240]
http://chess.grantnet.us/test/36564/
```
```
Elo   | -0.36 +- 3.02 (95%)
LLR   | -2.95 (-2.94, 2.94) [0.00, 5.00]
Games | N: 22396 W: 4938 L: 4961 D: 12497
Penta | [112, 2662, 5671, 2643, 110]
http://chess.grantnet.us/test/36565/
```
=> Adjust TT replacement scheme for matching keys

src/SearchData.h, src/main.cpp
```
Elo   | 0.60 +- 3.25 (95%)
Games | N: 19692 W: 4454 L: 4420 D: 10818
Penta | [111, 2313, 4965, 2345, 112]
http://chess.grantnet.us/test/36587/
```
=> Use hardware_destructive_interference_size to avoid false sharing

src/main.cpp
```
$ python3 ./speedup.py 
Halogen-11.11.1.exe         |       Halogen-pext-avx2.exe        |
mu              sigma       |        mu              sigma       |   Sp(1)/Sp(2)      3*sigma   
------------------------------------+------------------------------------+------------------------------------
4041750.000          3594.645|       5051525.000          4330.273|     -19.988 %  +/-  0.251 %
```
Improves bench speed by around 20%. Regular search is unaffected.
=> Don't clear the hash table between bench searches

src/History.cpp, src/Search.cpp
```
Elo   | -0.30 +- 2.52 (95%)
Games | N: 35984 W: 8849 L: 8880 D: 18255
Penta | [459, 4295, 8482, 4330, 426]
http://chess.grantnet.us/test/36726/
```
=> Average across history tables

src/Makefile, src/TTEntry.h, src/TranspositionTable.cpp, src/TranspositionTable.h, src/main.cpp
Large speedup (15%) when hash is large:
Before:
```
$ taskset -c 2 ./engines/Halogen-11.15.1.exe 
Halogen 11.15.1 x64 POPCNT
setoption name Hash value 16384
go movetime 60000
...
info depth 28 seldepth 41 score cp 42 time 45661 nodes 200983759 nps 4401000 hashfull 12 tbhits 0 pv d2d4 g8f6 g1f3 d7d5 c2c4 e7e6 g2g3 f8e7 f1g2 e8g8 e1g1 d5c4 d1a4 c7c5 d4c5 e7c5 a4c4 c5b6 b1c3 b8c6 f1d1 d8e7 c3a4 e6e5 a4b6 a7b6 c1g5 c8e6 c4c3
```
After:
```
$ taskset -c 2 ./engines/Halogen-pgo.exe 
Halogen 11.15.1 x64 POPCNT
setoption name Hash value 16384
go movetime 60000
...
info depth 28 seldepth 41 score cp 42 time 38262 nodes 200983759 nps 5252000 hashfull 12 tbhits 0 pv d2d4 g8f6 g1f3 d7d5 c2c4 e7e6 g2g3 f8e7 f1g2 e8g8 e1g1 d5c4 d1a4 c7c5 d4c5 e7c5 a4c4 c5b6 b1c3 b8c6 f1d1 d8e7 c3a4 e6e5 a4b6 a7b6 c1g5 …
```
=> Add huge page support

src/History.h, src/Search.cpp, src/main.cpp
```
Elo   | 0.42 +- 2.36 (95%)
Games | N: 21608 W: 4785 L: 4759 D: 12064
Penta | [115, 2356, 5812, 2430, 91]
http://chess.grantnet.us/test/36832/
```
```Elo   | 0.76 +- 2.77 (95%)
LLR   | 3.06 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 19140 W: 4669 L: 4627 D: 9844
Penta | [189, 2232, 4709, 2228, 212]
http://chess.grantnet.us/test/36829/
```
=> Cap history adjustments

src/Search.cpp, src/Search.h, src/main.cpp
```
Elo   | 3.07 +- 2.43 (95%)
Games | N: 22624 W: 5158 L: 4958 D: 12508
Penta | [136, 2604, 5652, 2764, 156]
http://chess.grantnet.us/test/36849/
```
```
Elo   | 12.21 +- 6.14 (95%)
LLR   | 3.24 (-2.94, 2.94) [0.00, 5.00]
Games | N: 4328 W: 1182 L: 1030 D: 2116
Penta | [46, 473, 1005, 563, 77]
http://chess.grantnet.us/test/36847/
```
=> Tune LMR heuristic 

src/SearchData.cpp, src/main.cpp
```
Elo   | 4.77 +- 3.57 (95%)
Games | N: 12886 W: 3394 L: 3217 D: 6275
Penta | [193, 1409, 3070, 1570, 201]
http://chess.grantnet.us/test/36906/
```
=> Update the best move when in multi PV mode

src/History.h
```
Elo   | 4.25 +- 4.32 (95%)
Games | N: 6698 W: 1558 L: 1476 D: 3664
Penta | [31, 723, 1774, 775, 46]
http://chess.grantnet.us/test/36927/
```
```
Elo   | 1.03 +- 2.99 (95%)
Games | N: 16594 W: 4146 L: 4097 D: 8351
Penta | [170, 1919, 4107, 1894, 207]
http://chess.grantnet.us/test/36926/
```
=> Correctly cap history scores

src/Magic.cpp, src/Makefile
With older versions of GCC, compiling constexpr magic bitboards in more than one translation unit causes the memory usage to exceed 8GB. This PR limits constexpr magic bitboards to a single TU (`MoveGeneration.cpp`)
=> Fix compiler OOM issues

src/Magic.h
Causing issues on openbench using up too much memory when compiling.
=> Remove constexpr magic bitboards

src/Search.cpp, src/main.cpp
Baseline:
```
Total fens:    6556
Found mates:   1040
Best mates:    699
Complete PVs:  1031/1040 (99.1%)
Complete best PVs:  699/699(100.0%)
```
Dev:
```
Total fens:    6556
Found mates:   1044
Best mates:    711
Complete PVs:  1035/1044 (99.1%)
Complete best PVs:  711/711 (100.0%)
```
```
Elo   | 0.24 +- 2.54 (95%)
Games | N: 24384 W: 6255 L: 6238 D: 11891
Penta | [351, 2738, 5974, 2801, 328]
http://chess.grantnet.us/test/37097/
```
=> Correctly apply mate distance pruning

src/Search.cpp, src/main.cpp
```
Elo   | 5.88 +- 3.98 (95%)
Games | N: 8456 W: 1975 L: 1832 D: 4649
Penta | [50, 931, 2142, 1036, 69]
http://chess.grantnet.us/test/37112/
```
```
Elo   | 6.66 +- 4.47 (95%)
Games | N: 8188 W: 2124 L: 1967 D: 4097
Penta | [110, 928, 1859, 1089, 108]
http://chess.grantnet.us/test/37105/
```
=> Adjust singular extensions sbeta formula

src/Search.cpp, src/SearchData.h, src/main.cpp
```
Elo   | -1.63 +- 1.79 (95%)
LLR   | -0.94 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 42088 W: 9539 L: 9737 D: 22812
Penta | [283, 5066, 10535, 4886, 274]
http://chess.grantnet.us/test/37126/
```
```
Elo   | 1.28 +- 3.18 (95%)
Games | N: 15176 W: 3816 L: 3760 D: 7600
Penta | [178, 1772, 3635, 1822, 181]
http://chess.grantnet.us/test/37123/
```
Zugzwang test positions (100m nodes, 512MB hash):
Baseline:
```
Summary of Results:
Total positions: 36
Correctly identified best moves: 21
Success rate: 58.33%
```
Dev:
```
Summary of Results:
Total positions: 36
Correctly identified best moves: 23
Success rate: 63.89%
```
=> Implement enhanced null move pruning verification

src/Search.cpp, src/SearchConstants.h, src/main.cpp
```
Elo   | 4.15 +- 3.12 (95%)
Games | N: 13492 W: 3105 L: 2944 D: 7443
Penta | [75, 1535, 3362, 1702, 72]
http://chess.grantnet.us/test/37168/
```
```
Elo   | -0.90 +- 3.03 (95%)
LLR   | -2.95 (-2.94, 2.94) [0.00, 5.00]
Games | N: 17742 W: 4489 L: 4535 D: 8718
Penta | [254, 2130, 4146, 2090, 251]
http://chess.grantnet.us/test/37167/
```
=> Adjust futility pruning scheme with a quadratic

src/Search.cpp, src/SearchConstants.h, src/main.cpp
```
Elo   | 22.84 +- 8.65 (95%)
Games | N: 1828 W: 457 L: 337 D: 1034
Penta | [9, 169, 447, 271, 18]
http://chess.grantnet.us/test/37241/
```
```
Elo   | 26.73 +- 9.90 (95%)
Games | N: 1784 W: 512 L: 375 D: 897
Penta | [21, 168, 398, 263, 42]
http://chess.grantnet.us/test/37240/
```
=> SPSA LTC tune

src/Search.cpp, src/main.cpp
```
Elo   | 9.48 +- 5.27 (95%)
Games | N: 4658 W: 1079 L: 952 D: 2627
Penta | [23, 492, 1177, 609, 28]
http://chess.grantnet.us/test/37313/
```
```
Elo   | 9.99 +- 5.61 (95%)
LLR   | 3.04 (-2.94, 2.94) [0.00, 5.00]
Games | N: 5078 W: 1303 L: 1157 D: 2618
Penta | [62, 557, 1154, 705, 61]
http://chess.grantnet.us/test/37311/
```
=> Don't apply NMP if the tt_score is an upper-bound below beta

src/TranspositionTable.cpp, src/TranspositionTable.h, src/main.cpp, src/uci/uci.cpp, src/uci/uci.h
Supports variable (not power of 2) TT sizes with a index determined by the higher order bits of the key
```
Elo   | -0.66 +- 1.74 (95%)
Games | N: 52256 W: 13049 L: 13149 D: 26058
Penta | [702, 6197, 12404, 6149, 676]
http://chess.grantnet.us/test/37339/
```
=> Replace TT index function with mulhi_64 algorithm

src/TTEntry.h
```
Elo   | 0.10 +- 2.27 (95%)
LLR   | -2.95 (-2.94, 2.94) [0.00, 5.00]
Games | N: 30614 W: 7680 L: 7671 D: 15263
Penta | [414, 3585, 7284, 3626, 398]
http://chess.grantnet.us/test/37347/
```
=> Compress TT entries to 10 bytes

src/Search.cpp, src/main.cpp
```
Elo   | 0.66 +- 1.54 (95%)
LLR   | -2.96 (-2.94, 2.94) [0.00, 5.00]
Games | N: 56366 W: 12598 L: 12491 D: 31277
Penta | [339, 6679, 14053, 6760, 352]
http://chess.grantnet.us/test/37354/
```
```
Elo   | 2.53 +- 2.01 (95%)
Games | N: 40730 W: 10396 L: 10099 D: 20235
Penta | [551, 4862, 9274, 5095, 583]
http://chess.grantnet.us/test/37351/
```
=> Probe Transposition Table in Quiescence search

src/Network.cpp
```
Elo   | 38.65 +- 6.60 (95%)
Games | N: 5000 W: 1739 L: 1185 D: 2076
Penta | [78, 472, 988, 742, 220]
http://chess.grantnet.us/test/37368/
```
=> Adjust scale to 160

.github/workflows/regression-check.yml, src/Search.cpp, src/TTEntry.h, src/TranspositionTable.cpp, src/main.cpp, src/test/tsan.supp
```
Elo   | 2.22 +- 1.73 (95%)
Games | N: 47368 W: 11742 L: 11439 D: 24187
Penta | [381, 5571, 11505, 5818, 409]
http://chess.grantnet.us/test/37471/
```
=> Remove atomics in Transposition table

src/History.cpp
```
Elo   | 4.08 +- 3.17 (95%)
Games | N: 16450 W: 4322 L: 4129 D: 7999
Penta | [225, 1910, 3780, 2067, 243]
http://chess.grantnet.us/test/37483/
```
=> eval_correction_history_adj_depth

src/Search.cpp, src/main.cpp
```
Elo   | 5.16 +- 3.66 (95%)
Games | N: 10240 W: 2418 L: 2266 D: 5556
Penta | [67, 1171, 2496, 1315, 71]
http://chess.grantnet.us/test/37495/
```
```
Elo   | 11.00 +- 6.05 (95%)
Games | N: 4422 W: 1184 L: 1044 D: 2194
Penta | [46, 499, 1001, 599, 66]
http://chess.grantnet.us/test/37494/
```
=> Use TT evaluation to correct static eval

src/History.h
```
Elo   | 4.10 +- 3.14 (95%)
LLR   | 3.05 (-2.94, 2.94) [0.00, 5.00]
Games | N: 17464 W: 4619 L: 4413 D: 8432
Penta | [277, 2019, 3955, 2183, 298]
http://chess.grantnet.us/test/37500/
```
=> Adjust correction_max to 16

src/Search.cpp, src/main.cpp
```
Elo   | -0.71 +- 2.65 (95%)
LLR   | -2.96 (-2.94, 2.94) [0.00, 5.00]
Games | N: 18704 W: 4200 L: 4238 D: 10266
Penta | [125, 2190, 4734, 2204, 99]
http://chess.grantnet.us/test/37513/
```
```
Elo   | 1.99 +- 1.39 (95%)
Games | N: 85000 W: 21641 L: 21154 D: 42205
Penta | [1117, 10212, 19430, 10549, 1192]
http://chess.grantnet.us/test/37512/
```
=> Fix code for TT eval correction

src/Score.h, src/Search.cpp, src/main.cpp
```
Elo   | -0.56 +- 1.78 (95%)
LLR   | 3.04 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 48002 W: 11976 L: 12053 D: 23973
Penta | [570, 5635, 11683, 5528, 585]
http://chess.grantnet.us/test/37533/
```
=> Don't allow TT eval correction to return unproven mate scores in q-search

src/BoardState.cpp, src/BoardState.h, src/GameState.cpp, src/GameState.h, src/Makefile, src/Network.cpp, src/Network.h
Trained using 1.35B positions (datagen 3 + 4 + 5 + 6), filtered to remove captures and promotions. Non-mirrored 8 king bucket architecture.
```
File Path      : ...
Threads        : 20
WDL Proportion : start 0.3 end 0.3
Max Epochs     : 50
Save Rate      : 10
Batch Size     : 16384
Net Name       : bullet_r19_768x8-512x2-1x8
LR Scheduler   : start 0.001 gamma 0.95 drop every 1 epochs
Scale          : 160
Positions      : 1116214793
```
```
Elo   | 7.49 +- 4.70 (95%)
Games | N: 6588 W: 1805 L: 1663 D: 3120
Penta | [59, 711, 1628, 821, 75]
http://chess.grantnet.us/test/37573/
```
```
Elo   | 5.74 +- 4.15 (95%)
Games | N: 11268 W: 3329 L: …
```
=> Update default network to e9c3f4f5.nn

src/Makefile, src/Network.cpp, src/main.cpp
```
Elo   | 16.09 +- 7.10 (95%)
Games | N: 2614 W: 675 L: 554 D: 1385
Penta | [9, 266, 648, 363, 21]
http://chess.grantnet.us/test/37671/
```
```
Elo   | 13.95 +- 6.82 (95%)
Games | N: 3388 W: 932 L: 796 D: 1660
Penta | [36, 353, 793, 463, 49]
http://chess.grantnet.us/test/37670/
```
=> Implement enhanced SCReLU trick from Lizard engine

src/StagedMoveGenerator.cpp, src/main.cpp
```
Elo   | -0.13 +- 2.13 (95%)
Games | N: 31602 W: 7744 L: 7756 D: 16102
Penta | [300, 3708, 7799, 3692, 302]
http://chess.grantnet.us/test/37713/
```
=> Fix SEE function for en passant

src/TranspositionTable.cpp, src/main.cpp
```
Elo   | 1.92 +- 3.37 (95%)
Games | N: 11762 W: 2889 L: 2824 D: 6049
Penta | [69, 1357, 2993, 1364, 98]
http://chess.grantnet.us/test/37752/
```
=> Fix overflow in calculating TT entry score

src/Makefile, src/main.cpp
| datagen7+8 | 12.0.0                                        | 0.7B |
The combined dataset was [filtered](https://github.com/KierenP/Halogen/blob/e49385f990a750a6bbbaf7320a0b47d010be116e/src/datagen/filter.h) to remove positions where the best move is a capture, promotion, or positions in check. The dataset was then shuffled.
The bullet trainer was used with [config](https://github.com/jw1912/bullet/blob/d4033b515f17bafa596c714ac969269217ab6a53/examples/halogen.rs). …
=> Update default network to 9819aa87.nn

src/Makefile, src/main.cpp
| datagen7+8+9 | 12.0.0                                        | 1.9B |
The combined dataset was [filtered](https://github.com/KierenP/Halogen/blob/e49385f990a750a6bbbaf7320a0b47d010be116e/src/datagen/filter.h) to remove positions where the best move is a capture, promotion, or positions in check. The dataset was then shuffled.
The bullet trainer was used with [config](https://github.com/jw1912/bullet/blob/b27b9bab0c23715d1c5b768a2211f9c19a02ce9c/examples/halogen.rs). …
=> Update default network to 46f749a2.nn

src/Makefile, src/main.cpp
| datagen7..13| 12.0.0                                        | 4.0B |
The combined dataset was [filtered](https://github.com/KierenP/Halogen/blob/e49385f990a750a6bbbaf7320a0b47d010be116e/src/datagen/filter.h) to remove positions where the best move is a capture, promotion, or positions in check. The dataset was then shuffled.
The bullet trainer was used with [config](https://github.com/KierenP/bullet/blob/24921649e13656603941339b0a42ef84f1c319d4/examples/halogen.rs). …
=> Update default network to 6913d330.nn

src/Search.cpp, src/main.cpp, src/test/tsan.supp
Every pruning / reduction / extension technique that uses the static eval is not applied when in check, so this change is non-functional. Speedup is `0.466 %  +/-  0.085 %`
=> Avoid calculating static eval when in check

src/Search.cpp, src/main.cpp
```
Elo   | 5.36 +- 3.03 (95%)
Games | N: 13350 W: 3259 L: 3053 D: 7038
Penta | [45, 1483, 3416, 1683, 48]
http://chess.grantnet.us/test/38088/
```
```
Elo   | 1.37 +- 1.07 (95%)
Games | N: 124142 W: 30527 L: 30039 D: 63576
Penta | [1030, 14795, 29924, 15301, 1021]
http://chess.grantnet.us/test/38080/
```
=> Adjust static evaluation based on 50 move rule

src/MoveList.h, src/Search.cpp, src/StagedMoveGenerator.cpp, src/StagedMoveGenerator.h, src/StaticExchangeEvaluation.cpp, src/StaticExchangeEvaluation.h, src/test/StaticExchangeEvaluation.cpp
```
Elo   | 4.84 +- 2.91 (95%)
Games | N: 15866 W: 3977 L: 3756 D: 8133
Penta | [101, 1760, 4010, 1941, 121]
http://chess.grantnet.us/test/38094/
```
=> Implement smart SEE for inequality checks

src/Search.cpp, src/main.cpp
```
Elo   | -0.50 +- 1.75 (95%)
LLR   | 2.94 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 45046 W: 11060 L: 11125 D: 22861
Penta | [348, 5290, 11328, 5193, 364]
http://chess.grantnet.us/test/38115/
```
=> Limit the 50 move rule eval adjustment

src/MoveList.h, src/Search.cpp, src/StagedMoveGenerator.cpp, src/StagedMoveGenerator.h, src/StaticExchangeEvaluation.cpp, src/StaticExchangeEvaluation.h, src/main.cpp, src/test/StaticExchangeEvaluation.cpp
```
Elo   | 2.48 +- 1.84 (95%)
Games | N: 35116 W: 8358 L: 8107 D: 18651
Penta | [97, 4022, 9057, 4297, 85]
http://chess.grantnet.us/test/38111/
```
```
Elo   | 7.00 +- 3.62 (95%)
Games | N: 10368 W: 2632 L: 2423 D: 5313
Penta | [58, 1162, 2556, 1329, 79]
http://chess.grantnet.us/test/38110/
```
=> Order loud moves by MVV-LVA

src/Search.cpp, src/main.cpp
```
Elo   | -0.48 +- 1.54 (95%)
Games | N: 47302 W: 10996 L: 11062 D: 25244
Penta | [133, 5243, 12969, 5169, 137]
http://chess.grantnet.us/test/38123/
```
```
Elo   | 0.32 +- 2.42 (95%)
Games | N: 23136 W: 5753 L: 5732 D: 11651
Penta | [186, 2634, 5896, 2677, 175]
http://chess.grantnet.us/test/38122/
```
=> Simplify q-search delta prune

src/History.cpp, src/History.h, src/Search.cpp, src/SearchData.cpp, src/SearchData.h, src/StagedMoveGenerator.cpp, src/StagedMoveGenerator.h, src/main.cpp
```
Elo   | 3.33 +- 2.26 (95%)
Games | N: 23672 W: 5635 L: 5408 D: 12629
Penta | [82, 2670, 6083, 2941, 60]
http://chess.grantnet.us/test/38157/
```
```
Elo   | 3.41 +- 2.36 (95%)
Games | N: 25232 W: 6327 L: 6079 D: 12826
Penta | [173, 2979, 6099, 3157, 208]
http://chess.grantnet.us/test/38155/
```
=> Add capture history heuristic

src/MoveGeneration.cpp, src/MoveList.h, src/SearchData.h, src/main.cpp
Seeing a +3% speedup for non-pgo builds. PGO builds are even.
```
Elo   | 0.06 +- 2.31 (95%)
LLR   | -0.87 (-2.94, 2.94) [0.00, 3.00]
Games | N: 25036 W: 6081 L: 6077 D: 12878
Penta | [166, 2928, 6342, 2900, 182]
http://chess.grantnet.us/test/38160/
```
=> Speedup movegen functions

src/Makefile, src/main.cpp
`-fprofile-partial-training` and `--sparse=true` omit PGO information for functions that aren't called during the profiling pass. Without these flags, the unused functions are optimized for space rather than speed. This is not ideal, because there are parts of the hot-path that are not ran during the PGO build (Syzygy TB e.g)
=> Optimize PGO flags

src/History.h, src/Search.cpp, src/StagedMoveGenerator.cpp, src/main.cpp
```
Elo   | 1.90 +- 1.50 (95%)
Games | N: 53372 W: 12617 L: 12325 D: 28430
Penta | [147, 6198, 13703, 6492, 146]
http://chess.grantnet.us/test/38182/
```
```
Elo   | 1.66 +- 1.34 (95%)
Games | N: 79194 W: 19555 L: 19177 D: 40462
Penta | [624, 9421, 19136, 9785, 631]
http://chess.grantnet.us/test/38177/
```
=> Tune history values

src/History.cpp, src/Search.cpp, src/SearchData.cpp, src/SearchData.h, src/main.cpp
```
Elo   | -0.02 +- 1.30 (95%)
LLR   | 2.95 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 81378 W: 19696 L: 19701 D: 41981
Penta | [574, 9789, 19952, 9816, 558]
http://chess.grantnet.us/test/38190/
```
=> Fix continuation history heuristic

src/BoardState.cpp, src/BoardState.h, src/GameState.cpp, src/MoveGeneration.cpp, src/MoveGeneration.h, src/main.cpp
Tested `perft 6` from startpos:
Old perft speed: `301565844 nps`
new perft speed: `320797869 nps`
```
Elo   | 0.61 +- 2.52 (95%)
Games | N: 19322 W: 4631 L: 4597 D: 10094
Penta | [95, 2161, 5120, 2185, 100]
http://chess.grantnet.us/test/38207/
```
=> Speedup Bitboard representation

src/History.cpp, src/History.h, src/SearchData.h
```
Elo   | 1.56 +- 1.26 (95%)
Games | N: 75972 W: 17859 L: 17518 D: 40595
Penta | [200, 8846, 19577, 9139, 224]
http://chess.grantnet.us/test/38211/
```
```
Elo   | 1.60 +- 1.29 (95%)
Games | N: 84696 W: 20763 L: 20372 D: 43561
Penta | [640, 10057, 20643, 10288, 720]
http://chess.grantnet.us/test/38208/
```
=> Add Follow move history heuristic

src/BoardState.cpp, src/BoardState.h, src/History.cpp, src/History.h, src/Zobrist.cpp, src/Zobrist.h, src/main.cpp
```
Elo   | 1.70 +- 1.36 (95%)
Games | N: 64644 W: 15243 L: 14927 D: 34474
Penta | [162, 7572, 16539, 7886, 163]
http://chess.grantnet.us/test/38215/
```
```
Elo   | 1.51 +- 1.21 (95%)
Games | N: 93398 W: 22809 L: 22403 D: 48186
Penta | [601, 11170, 22811, 11456, 661]
http://chess.grantnet.us/test/38213/
```
=> Add pawn hash indexed history tables for ordering quiet moves

src/History.cpp, src/History.h, src/MoveGeneration.cpp, src/MoveGeneration.h, src/Search.cpp, src/SearchData.cpp, src/SearchData.h, src/main.cpp
```
Elo   | 1.51 +- 1.22 (95%)
Games | N: 81408 W: 19347 L: 18994 D: 43067
Penta | [232, 9435, 21033, 9756, 248]
http://chess.grantnet.us/test/38220/
```
```
Elo   | 2.92 +- 2.12 (95%)
Games | N: 30842 W: 7652 L: 7393 D: 15797
Penta | [204, 3614, 7566, 3793, 244]
http://chess.grantnet.us/test/38219/
```
=> Add quiet move threat history

src/SearchData.cpp, src/SearchData.h, src/uci/uci.cpp, src/uci/uci.h
In the old logic, a fail high followed by a fail low could cause the fail low to overwrite the data pointed to by `best_search_result_`. Fail low results have no PV and usually a nonsensical best move. 
This caused the blunder [here](https://www.chess.com/computer-chess-championship#event=ccc23-bullet-qualifier-1&game=552).  Event logs clearly show a `upperbound` score made it's way into the bestmove:
------------------
Details:
A fail high can result in the best move being updated. This is intentional and increases strength.
```
if ((result_data.type == SearchResultType::EXACT || result_data.type == SearchResultType::LOWER_BOUND)
&& (!best_search_result_ || (best_search_result_->depth < result_data.depth)
|| (best_search_result_->depth == result_data.depth && best_search_result_->score < …
```
=> Fix potential blunder where a fail-low score overwrites the best move

src/History.cpp
Using `ss->moved_piece` is wrong, because we use history scores before we actually apply any of the moves in the search loop.
=> Remove redundant TODO comments

src/Search.cpp, src/main.cpp
```
Elo   | 52.30 +- 13.64 (95%)
Games | N: 830 W: 254 L: 130 D: 446
Penta | [1, 57, 201, 129, 27]
```
=> Bugfix: Fix illegal move and empty PV in TB win root node

src/GameState.cpp, src/Search.cpp, src/SearchData.h, src/StaticVector.h
```
Elo   | -0.07 +- 1.21 (95%)
LLR   | 2.97 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 88024 W: 21755 L: 21774 D: 44495
Penta | [649, 9706, 23244, 9841, 572]
http://chess.grantnet.us/test/38961/
```
=> Trim previousStates vector

src/SearchData.cpp, src/main.cpp
```
Elo   | 3.29 +- 2.28 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 3.00]
Games | N: 25990 W: 6528 L: 6282 D: 13180
Penta | [176, 2930, 6566, 3118, 205]
```
```
Elo   | 1.54 +- 1.56 (95%)
LLR   | 1.87 (-2.94, 2.94) [0.00, 3.00]
Games | N: 50438 W: 11744 L: 11521 D: 27173
Penta | [156, 5896, 12914, 6075, 178]
```
=> Allow exact search results to replace lower-bound results even when the score is lower

src/BoardState.cpp, src/Move.cpp, src/Move.h, src/MoveGeneration.cpp, src/MoveGeneration.h, src/main.cpp
Perft speed calculated by
```
taskset -c 1 ../bin/Halogen-native "position fen r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - " "perft 7"
```
Baseline:
`Nodes searched: 374190009323 in 1065.81 seconds (351085914 nps)`
Dev: 
`Nodes searched: 374190009323 in 1001.54 seconds (373615407 nps)`
=> Speedup movegen by 6%

src/Search.cpp, src/StaticExchangeEvaluation.h, src/main.cpp, src/test/StaticExchangeEvaluation.cpp
```
Elo   | 3.43 +- 2.37 (95%)
Games | N: 25550 W: 6447 L: 6195 D: 12908
Penta | [202, 2993, 6166, 3179, 235]
```
```
Elo   | 1.43 +- 1.15 (95%)
Games | N: 91800 W: 22101 L: 21722 D: 47977
Penta | [310, 10685, 23511, 11104, 290]
```
=> Static exchange pruning for quiet moves

src/BoardState.h, src/GameState.cpp, src/GameState.h, src/Search.cpp, src/main.cpp
```
Elo   | 5.76 +- 3.91 (95%)
Games | N: 8500 W: 2161 L: 2020 D: 4319
Penta | [41, 931, 2190, 1022, 66]
http://chess.grantnet.us/test/39073/
```
```
Elo   | 5.55 +- 7.04 (95%)
LLR   | 0.55 (-2.94, 2.94) [0.00, 3.00]
Games | N: 2252 W: 544 L: 508 D: 1200
Penta | [2, 241, 608, 269, 6]
http://chess.grantnet.us/test/39074/
```
=> Improve repetition detection algorithm

src/Search.cpp, src/main.cpp
```
Elo   | 0.42 +- 0.96 (95%)
LLR   | -2.69 (-2.94, 2.94) [0.00, 3.00]
Games | N: 148296 W: 35847 L: 35668 D: 76781
Penta | [1047, 17678, 36486, 17923, 1014]
http://chess.grantnet.us/test/39081/
```
=> Add upcoming cycle detection to qsearch

src/Search.cpp, src/StagedMoveGenerator.cpp, src/main.cpp
```
Elo   | 0.73 +- 1.04 (95%)
LLR   | -0.47 (-2.94, 2.94) [0.00, 3.00]
Games | N: 126908 W: 30809 L: 30541 D: 65558
Penta | [830, 15248, 31072, 15432, 872]
http://chess.grantnet.us/test/39095/
```
=> Use TT move in q-search where possible

src/History.cpp, src/History.h, src/Search.cpp, src/SearchData.cpp, src/SearchData.h, src/main.cpp
https://www.chessprogramming.org/Static_Evaluation_Correction_History
```
Elo   | 3.34 +- 2.31 (95%)
Games | N: 25450 W: 6343 L: 6098 D: 13009
Penta | [167, 2947, 6250, 3196, 165]
http://chess.grantnet.us/test/39100/
```
=> Add Pawn Correction History

src/Search.cpp, src/main.cpp
```
Elo   | -0.63 +- 1.53 (95%)
LLR   | 2.94 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 54440 W: 13157 L: 13255 D: 28028
Penta | [363, 6109, 14325, 6109, 314]
http://chess.grantnet.us/test/39110/
```
=> Correctly cap adjusted eval

src/Search.cpp, src/main.cpp
```
Elo   | -0.32 +- 1.55 (95%)
LLR   | -2.96 (-2.94, 2.94) [0.00, 3.00]
Games | N: 56782 W: 13630 L: 13683 D: 29469
Penta | [391, 6858, 13952, 6793, 397]
```
=> Adjust eval correction condition

src/StagedMoveGenerator.cpp, src/StagedMoveGenerator.h, src/main.cpp
```
Elo   | 4.04 +- 3.11 (95%)
LLR   | 2.05 (-2.94, 2.94) [0.00, 3.00]
Games | N: 13320 W: 3291 L: 3136 D: 6893
Penta | [73, 1461, 3454, 1582, 90]
http://chess.grantnet.us/test/39133/
```
=> Use partial selection sort to speedup StagedMoveGeneration

src/Search.cpp, src/main.cpp
```
Elo   | 0.01 +- 2.10 (95%)
Games | N: 28940 W: 6967 L: 6966 D: 15007
Penta | [176, 3285, 7542, 3296, 171]
http://chess.grantnet.us/test/39153/
```
=> Fix 50 move rule edge case handling

src/Makefile, src/main.cpp
| datagen7..13| 12.0.0                                        | 4.0B |
The combined dataset was [filtered](https://github.com/KierenP/Halogen/blob/e49385f990a750a6bbbaf7320a0b47d010be116e/src/datagen/filter.h) to remove positions where the best move is a capture, promotion, or positions in check. The dataset was then shuffled, and finally [rescored](https://github.com/KierenP/Halogen/blob/e49385f990a750a6bbbaf7320a0b47d010be116e/src/datagen/syzygy_rescore.h)
The bullet trainer …
=> Update default network to 87b3ca62.nn

src/Makefile, src/main.cpp
Exactly the same training procedure as r46 (previous master) but with 1000 SBs rather than 400 SBs.
----------------------------
| datagen7..13| 12.0.0                                        | 4.0B |
The combined dataset was [filtered](https://github.com/KierenP/Halogen/blob/e49385f990a750a6bbbaf7320a0b47d010be116e/src/datagen/filter.h) to remove positions where the best move is a capture, promotion, or positions in check. The dataset was then shuffled, and finally …
=> Update default network to b425ef8d.nn

src/BoardState.cpp, src/BoardState.h, src/History.cpp, src/History.h, src/Search.cpp, src/SearchData.cpp, src/SearchData.h, src/Zobrist.cpp, src/Zobrist.h, src/main.cpp
```
Elo   | 1.58 +- 1.42 (95%)
LLR   | 2.39 (-2.94, 2.94) [0.00, 3.00]
Games | N: 59048 W: 14006 L: 13737 D: 31305
Penta | [134, 6884, 15231, 7129, 146]
http://chess.grantnet.us/test/39458/
```
```
Elo   | -2.70 +- 2.71 (95%)
LLR   | -2.98 (-2.94, 2.94) [0.00, 3.00]
Games | N: 18530 W: 4419 L: 4563 D: 9548
Penta | [130, 2279, 4588, 2141, 127]
http://chess.grantnet.us/test/39457/
```
=> Non pawn correction history

src/Search.cpp, src/main.cpp
```
Elo   | 7.79 +- 3.85 (95%)
Games | N: 9416 W: 2382 L: 2171 D: 4863
Penta | [60, 1060, 2272, 1241, 75]
http://chess.grantnet.us/test/39470/
```
```
Elo   | 7.84 +- 3.75 (95%)
Games | N: 8552 W: 2086 L: 1893 D: 4573
Penta | [19, 942, 2159, 1139, 17]
http://chess.grantnet.us/test/39491/
```
=> Use fail-medium for RFP fail-high cutoffs

src/Search.cpp, src/SearchData.h, src/main.cpp
```
Elo   | 10.23 +- 4.39 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 3.00]
Games | N: 6656 W: 1655 L: 1459 D: 3542
Penta | [27, 690, 1726, 830, 55]
http://chess.grantnet.us/test/39496/
```
```
Elo   | 12.48 +- 4.76 (95%)
LLR   | 2.94 (-2.94, 2.94) [0.00, 3.00]
Games | N: 5012 W: 1226 L: 1046 D: 2740
Penta | [6, 498, 1324, 666, 12]
http://chess.grantnet.us/test/39500/
```
=> Use 'improving' heuristic to more optimistically apply RFP

.gitattributes, .github/workflows/fastchess.yml, .github/workflows/matetrack.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, .gitignore, network/b425ef8d.nn, src/Makefile, src/main.cpp
https://github.com/KierenP/Halogen-Networks will continue to exist in order to support building older versions of Halogen, but newer versions will leverage git-lfs
=> Use git lfs to host network files

src/EGTB.cpp, src/main.cpp
`TB_RESULT_STALEMATE` and `TB_RESULT_CHECKMATE` don't get returned by `tb_probe_wdl` and conflict with legitimate draw and win scores that are returned.
This also fixes an additional bug with `tb_probe_root_dtz`, where the results were being incorrectly sorted invoking undefined behaviour.
```
Elo   | -1.11 +- 4.93 (95%)
Games | N: 5012 W: 1154 L: 1170 D: 2688
Penta | [20, 581, 1324, 557, 24]
http://chess.grantnet.us/test/39518/
```
=> Fix Syzygy WDL probe during search

.gitattributes, network/4ed21ecb.nn, network/b425ef8d.nn, src/Makefile, src/main.cpp
Trained r70 using 0.4 constant WDL rather than 0.3 constant WDL used by r62. Then trained r71 using 0.5 constant WDL.
----------------------------
| datagen7..13| 12.0.0                                        | 4.0B |
The combined dataset was converted into viribinpack using [link](https://github.com/KierenP/Halogen/blob/ebd0b3572c524c91234d2629f370eebf833f92a3/src/datagen/convert_to_viribinpack.h), the files were interleaved.
The bullet trainer was used with …
=> Update default network to 4ed21ecb.nn

src/Search.cpp, src/main.cpp
```
Elo   | 0.65 +- 1.68 (95%)
LLR   | 2.95 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 43048 W: 10263 L: 10183 D: 22602
Penta | [222, 4740, 11506, 4848, 208]
http://chess.grantnet.us/test/39547/
```
=> Avoid returning false mate scores from multi-cut

src/Search.cpp, src/SearchData.h, src/main.cpp
```
Elo   | -0.63 +- 1.52 (95%)
LLR   | 0.29 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 49326 W: 11169 L: 11258 D: 26899
Penta | [83, 5747, 13095, 5652, 86]
http://chess.grantnet.us/test/39580/
```
=> Simplify condition for limiting singular extensions

src/search/search.cpp
```
Elo   | 0.27 +- 1.05 (95%)
LLR   | -2.96 (-2.94, 2.94) [0.00, 3.00]
Games | N: 119504 W: 28431 L: 28339 D: 62734
Penta | [652, 14262, 29835, 14348, 655]
http://chess.grantnet.us/test/39655/
```
=> Research alpha raising nodes that fail high above beta

src/main.cpp, src/search/search.cpp
```
Elo   | 0.49 +- 1.28 (95%)
LLR   | -0.89 (-2.94, 2.94) [0.00, 3.00]
Games | N: 70286 W: 16457 L: 16357 D: 37472
Penta | [110, 8265, 18269, 8413, 86]
http://chess.grantnet.us/test/39789/
```
```
Elo   | 1.07 +- 1.19 (95%)
LLR   | 1.21 (-2.94, 2.94) [0.00, 3.00]
Games | N: 92484 W: 22059 L: 21773 D: 48652
Penta | [445, 11083, 22898, 11373, 443]
http://chess.grantnet.us/test/39784/
```
=> Generalised double extensions

src/main.cpp, src/search/search.cpp
```
Elo   | 5.02 +- 2.93 (95%)
Games | N: 14466 W: 3595 L: 3386 D: 7485
Penta | [39, 1664, 3632, 1845, 53]
http://chess.grantnet.us/test/39963/
```
=> Apply double negative extensions for non-singular cut ndoes

src/search/search.cpp
```
Elo   | 0.94 +- 1.86 (95%)
LLR   | 2.98 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 36268 W: 8591 L: 8493 D: 19184
Penta | [137, 4303, 9172, 4369, 153]
http://chess.grantnet.us/test/39974/
```
```
Elo   | -0.59 +- 2.93 (95%)
LLR   | 0.09 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 12848 W: 3015 L: 3037 D: 6796
Penta | [13, 1499, 3414, 1493, 5]
http://chess.grantnet.us/test/39975/
```
=> Simplify double extensions to only non-pv nodes

src/main.cpp, src/search/staged_movegen.cpp
```
Elo   | 4.37 +- 2.68 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 3.00]
Games | N: 17400 W: 4206 L: 3987 D: 9207
Penta | [71, 1958, 4415, 2193, 63]
http://chess.grantnet.us/test/39985/
```
=> Adjust good loud move margin to -100

src/main.cpp, src/search/staged_movegen.cpp, src/spsa/tuneable.h, src/uci/uci.cpp
```
Elo   | 4.82 +- 2.86 (95%)
Games | N: 15206 W: 3746 L: 3535 D: 7925
Penta | [45, 1727, 3871, 1892, 68]
http://chess.grantnet.us/test/39993/
```
=> Scale good loud SEE margin by move history

src/chessboard/board_state.cpp, src/chessboard/board_state.h, src/main.cpp, src/movegen/movegen.cpp, src/movegen/movegen.h, src/search/data.h, src/search/history.cpp, src/search/search.cpp
```
Elo   | 0.53 +- 1.48 (95%)
LLR   | 2.95 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 44904 W: 10837 L: 10769 D: 23298
Penta | [114, 4237, 13699, 4271, 131]
http://chess.grantnet.us/test/40006/
```
=> Refactor 'threats' logic into BoardState

src/main.cpp, src/movegen/list.h, src/movegen/movegen.cpp, src/search/staged_movegen.cpp, src/search/staged_movegen.h, src/utility/static_vector.h
Need to fix warnings, and segfault in search
------
Baseline: `Nodes searched: 8031647685 in 15.8891 seconds (505480301 nps)`
Dev: `Nodes searched: 8031647685 in 12.3739 seconds (649077260 nps)`
28.4% perft speedup
-----
Elo   | 2.87 +- 1.95 (95%)
LLR   | 3.03 (-2.94, 2.94) [0.00, 3.00]
Games | N: 25466 W: 6244 L: 6034 D: 13188
Penta | [59, 2302, 7807, 2500, 65]
http://chess.grantnet.us/test/40008/
=> Use AVX512_VBMI2 instructions to speed up movegen

src/main.cpp, src/network/inference.hpp
`3.399 %  +/-  0.733 %` speedup
```
Elo   | 7.04 +- 3.45 (95%)
SPRT  | 4.0+0.04s Threads=1 Hash=8MB
LLR   | 3.06 (-2.94, 2.94) [0.00, 3.00]
Games | N: 9866 W: 2528 L: 2328 D: 5010
Penta | [39, 980, 2708, 1154, 52]
http://chess.grantnet.us/test/40010/
```
=> Use compress_epi16 to process 32 blocks of 4 FT activations at once

src/Makefile, src/main.cpp, src/movegen/movegen.cpp, src/network/inference.hpp, src/network/simd/definitions.hpp
`1.183 %  +/-  0.217 %` speedup
Bench: 7609093
=> Use dpbusd, mask_compressstoreu, to speedup Zen5 builds

.github/workflows/fastchess.yml, .github/workflows/prerelease.yml, src/Makefile, src/main.cpp
Increased WDL from 0.5 to 0.7
| datagen7..15| 12.0.0                                        | 8.2B |
The bullet trainer was used with [config](https://github.com/KierenP/bullet/blob/c9df285d560dbf7aaefbfa0d8cf22adbcdd6e1f6/examples/halogen.rs).
-----------------------------
failed STC
```
Elo   | -7.52 +- 4.13 (95%)
LLR   | -3.01 (-2.94, 2.94) [0.00, 3.00]
Games | N: 7814 W: 1857 L: 2026 D: 3931
Penta | [48, 1028, 1914, 879, 38] …
```
=> Update default network to b5e00695.nn

src/chessboard/board_state.cpp, src/chessboard/board_state.h, src/datagen/datagen.cpp, src/main.cpp, src/movegen/movegen.cpp, src/movegen/movegen.h, src/search/search.cpp
```
Elo   | -1.27 +- 1.25 (95%)
SPRT  | 4.0+0.04s Threads=1 Hash=8MB
LLR   | -1.95 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 69640 W: 16958 L: 17213 D: 35469
Penta | [365, 6883, 20523, 6740, 309]
http://chess.grantnet.us/test/40043/
```
=> Calculate pinned and checker masks in board state

src/main.cpp, src/search/search.cpp
```
Elo   | 3.99 +- 3.10 (95%)
LLR   | 2.96 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 12964 W: 3191 L: 3042 D: 6731
Penta | [52, 1460, 3308, 1611, 51]
http://chess.grantnet.us/test/40061/
```
=> Don't track depth in qsearch

src/main.cpp, src/movegen/movegen.cpp
2.5% perft speedup
```
Before: Nodes searched: 3195901860 in 12.5357 seconds (254944192 nps)
After: Nodes searched: 3195901860 in 12.2229 seconds (261468296 nps)
```
Changes bench. Likely should test as nonregr.
Bench: 6888592
=> Hoist pinned checks in movegen

src/main.cpp, src/search/search.cpp
```
Elo   | 2.89 +- 2.07 (95%)
Games | N: 29290 W: 7161 L: 6917 D: 15212
Penta | [122, 3356, 7432, 3626, 109]
http://chess.grantnet.us/test/40136/
```
=> Don't apply TT eval correction in singular nodes

src/main.cpp, src/search/search.cpp, src/spsa/tuneable.h, src/uci/uci.cpp
```
Elo   | 2.26 +- 1.73 (95%)
Games | N: 41584 W: 10053 L: 9783 D: 21748
Penta | [143, 4838, 10567, 5094, 150]
http://chess.grantnet.us/test/40143/
```
=> Allow fail high TT cutoffs with insufficient depth when tt score is sufficiently high

src/main.cpp, src/search/data.h, src/search/search.cpp, src/spsa/tuneable.h, src/uci/uci.cpp
```
Elo   | 1.33 +- 1.15 (95%)
LLR   | 2.48 (-2.94, 2.94) [0.00, 3.00]
Games | N: 96530 W: 22951 L: 22582 D: 50997
Penta | [415, 11396, 24290, 11733, 431]
http://chess.grantnet.us/test/40181/
```
=> Add hindsight extensions
