KierenP/Halogen

Halogen/src/Search.cpp

```
bench: 24734121
ELO   | 18.84 +- 9.87 (95%)
SPRT  | 12.0+0.12s Threads=1 Hash=8MB
Games | N: 3304 W: 1234 L: 1055 D: 1015
```

Added back aspiration windows

---

Halogen/src/BitBoard.cpp
Halogen/src/Move.cpp
Halogen/src/Move.h
Halogen/src/MoveGeneration.cpp
Halogen/src/MoveGeneration.h
Halogen/src/Position.cpp
Halogen/src/Position.h
Halogen/src/Search.cpp
Halogen/src/Search.h
Halogen/src/main.cpp

```
ELO   | 57.27 +- 18.37 (95%)
SPRT  | 12.0+0.12s Threads=1 Hash=8MB
Games | N: 1010 W: 442 L: 277 D: 291
```

Static exchange evaluation

---

Halogen/src/Search.cpp
Halogen/src/Search.h
Halogen/src/main.cpp

```
master vs Halogen 3.9
ELO   | 131.24 +- 29.68 (95%)
Games | N: 438 W: 237 L: 79 D: 122
```

Multithreading 2

---

Halogen/src/Search.cpp

```
Bench: 19382623
hash_move_first vs master DIFF
ELO   | 41.39 +- 15.06 (95%)
Games | N: 1400 W: 555 L: 389 D: 456
```

Try the hash move before generating other moves

---

Halogen/src/Evaluate.cpp

```
eval_rook_file_bonus vs master DIFF
ELO   | 61.74 +- 18.80 (95%)
LLR   | 3.03 (-2.94, 2.94) [0.00, 5.00]
Games | N: 944 W: 411 L: 245 D: 288
```

Add a bonus for a rook on a open or semi open file

---

Halogen/src/Evaluate.cpp
Halogen/src/main.cpp

```
Bench: 16386168
eval_tempo vs master DIFF
ELO   | 15.38 +- 8.77 (95%)
Games | N: 4160 W: 1526 L: 1342 D: 1292
```

Added a tempo bonus

---

Halogen/src/BitBoardDefine.cpp
Halogen/src/BitBoardDefine.h
Halogen/src/Evaluate.cpp
Halogen/src/Evaluate.h
Halogen/src/Search.cpp

```
pawn_blockade_2 vs master DIFF
ELO   | 5.74 +- 4.50 (95%)
Games | N: 15496 W: 5383 L: 5127 D: 4986
```

Pawn blockade 2

---

Halogen/src/Evaluate.cpp
Halogen/src/main.cpp

```
Bench: 13496025
eval_tune vs master DIFF
ELO   | 47.03 +- 16.57 (95%)
Games | N: 1256 W: 541 L: 372 D: 343
```

Tuned evaluation paramiters

---

Halogen/src/BoardParamiters.cpp
Halogen/src/BoardParamiters.h
Halogen/src/Evaluate.cpp
Halogen/src/Position.cpp
Halogen/src/Position.h
Halogen/src/main.cpp

Bench: 12140859
eval-castle vs master DIFF
ELO   | 2.98 +- 2.50 (95%)
LLR   | 2.05 (-2.94, 2.94) [0.00, 5.00]
Games | N: 49360 W: 16691 L: 16268 D: 16401

Added and tuned evaluation for casteling rights

---

Halogen/src/Move.cpp
Halogen/src/Move.h
Halogen/src/Search.cpp
Halogen/src/TTEntry.cpp
Halogen/src/TTEntry.h
Halogen/src/TranspositionTable.cpp
Halogen/src/TranspositionTable.h
Halogen/src/texel.cpp

```
transposition_ageing vs master DIFF
ELO   | 2.19 +- 8.61 (95%)
LLR   | 3.02 (-2.94, 2.94) [-10.00, 0.00]
Games | N: 4116 W: 1371 L: 1345 D: 1400
```

Transposition ageing

---

Halogen/src/Search.cpp

```
lmr_lessened vs master DIFF
ELO   | 34.78 +- 17.94 (95%)
LLR   | 3.03 (-2.94, 2.94) [0.00, 10.00]
Games | N: 832 W: 279 L: 196 D: 357
```

Lmr lessened

---

Halogen/src/BitBoard.cpp
Halogen/src/BitBoardDefine.cpp
Halogen/src/Evaluate.cpp
Halogen/src/Evaluate.h
Halogen/src/Makefile
Halogen/src/MoveGeneration.cpp
Halogen/src/PawnHashTable.cpp
Halogen/src/Position.cpp
Halogen/src/Search.cpp
Halogen/src/Search.h
Halogen/src/TTEntry.cpp
Halogen/src/TTEntry.h
Halogen/src/TranspositionTable.cpp
Halogen/src/TranspositionTable.h
Halogen/src/Zobrist.cpp
Halogen/src/main.cpp
Halogen/src/texel.cpp
Halogen/src/texel.h

All games against Halogen 5
```
ELO   | 108.54 +- 8.63 (95%)
LLR   | 0.05 (-2.94, 2.94) [0.00, 0.01]
Games | N: 4352 W: 2098 L: 781 D: 1473
```
```
ELO   | 197.26 +- 16.56 (95%)
SPRT  | 5.0+0.05s Threads=6 Hash=64MB
LLR   | 0.03 (-2.94, 2.94) [0.00, 0.01]
Games | N: 1495 W: 923 L: 155 D: 417
```
```
ELO   | 129.65 +- 16.98 (95%)
LLR   | 0.02 (-2.94, 2.94) [0.00, 0.01]
Games | N: 1138 W: 572 L: 166 D: 400
```
```
ELO   | 189.24 +- 39.91 (95%)
SPRT  | 20.0+0.2s Threads=6 Hash=256MB
LLR   | 0.01 (-2.94, 2.94) [0.00, 0.01]
Games | N: 288 W: 179 L: 36 D: 73
```

Release halogen 6

---

Halogen/src/BoardParamiters.cpp
Halogen/src/BoardParamiters.h
Halogen/src/Network.cpp
Halogen/src/Network.h
Halogen/src/Position.cpp
Halogen/src/Position.h
Halogen/src/Search.cpp
Halogen/src/Search.h
Halogen/src/TranspositionTable.cpp
Halogen/src/TranspositionTable.h

```
clean_up vs eval_net DIFF
ELO   | 16.02 +- 14.63 (95%)
LLR   | 3.05 (-2.94, 2.94) [-10.00, 0.00]
Games | N: 1302 W: 420 L: 360 D: 522
```

Bench: 6903401

---

Halogen/src/Search.cpp

```
fix_see vs master DIFF
ELO   | 40.92 +- 20.29 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 10.00]
Games | N: 708 W: 260 L: 177 D: 271
```

Bench: 5657597

---

Halogen/src/Position.cpp

```
ELO   | 77.55 +- 30.37 (95%)
LLR   | 3.08 (-2.94, 2.94) [0.00, 10.00]
Games | N: 419 W: 208 L: 116 D: 95
```

Update to better network

---

Halogen/src/Search.cpp

```
ELO   | 37.50 +- 14.94 (95%)
Games | N: 1702 W: 777 L: 594 D: 331
```

Bench: 7064546

---

Halogen/src/Search.cpp

```
ELO   | 6.66 +- 4.98 (95%)
Games | N: 11688 W: 3772 L: 3548 D: 4368
```

Bench: 7076615

---

Halogen/src/Search.cpp

```
ELO   | -6.93 +- 5.16 (95%)
LLR   | -2.97 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 11024 W: 3386 L: 3606 D: 4032
```
small regression is ok

Smp aspiration change

---

Halogen/src/Network.cpp
Halogen/src/Network.h
Halogen/src/Position.cpp
Halogen/src/Position.h

```
ELO   | -8.10 +- 5.78 (95%)
LLR   | -2.95 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 8752 W: 2663 L: 2867 D: 3222
```
Small regression is fine.

Bench: 7182442

---

Halogen/src/Search.cpp

```
ELO   | 9.19 +- 6.21 (95%)
Games | N: 7376 W: 2365 L: 2170 D: 2841
```

Bench: 6781520

---

Halogen/src/MoveOrder.cpp
Halogen/src/MoveOrder.h

Bench: 7482198
```
ELO   | 0.12 +- 3.29 (95%)
LLR   | -3.02 (-2.94, 2.94) [0.00, 5.00]
Games | N: 26240 W: 8050 L: 8041 D: 10149
```

Don't repeat the TT move

---

Halogen/src/Network.cpp
Halogen/src/Network.h

Bench: 6542305

---

Halogen/src/MoveGeneration.cpp
Halogen/src/MoveGeneration.h
Halogen/src/Search.cpp

Emergency fix

---

Halogen/src/Search.cpp
Halogen/src/Search.h
Halogen/src/TimeManage.cpp
Halogen/src/TimeManage.h
Halogen/src/main.cpp

Refactor time management. Non functional change

---

Halogen/src/Search.cpp
Halogen/src/main.cpp

```
ELO   | 16.09 +- 9.87 (95%)
LLR   | 3.08 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 2960 W: 988 L: 851 D: 1121
```

Aspiration refactor

---

Halogen/src/Network.cpp
Halogen/src/Network.h

Bench | 6189619
```
ELO   | 8.88 +- 6.10 (95%)
Games | N: 7792 W: 2541 L: 2342 D: 2909
```

Move branching of ReLU to outside neuron FeedForward

---

Halogen/src/BitBoard.cpp
Halogen/src/BitBoardDefine.cpp
Halogen/src/BitBoardDefine.h
Halogen/src/EvalCache.cpp
Halogen/src/MoveGeneration.cpp
Halogen/src/MoveGeneration.h
Halogen/src/Network.cpp
Halogen/src/Network.h
Halogen/src/Position.cpp

Bench: 6189619
```
ELO   | 3.61 +- 5.63 (95%)
Games | N: 9136 W: 2906 L: 2811 D: 3419
```

Fix various warnings and style changes

---

Halogen/src/Position.cpp
Halogen/src/Position.h
Halogen/src/Search.cpp
Halogen/src/Search.h
Halogen/src/main.cpp

Bench: 6148096
```
ELO   | 51.33 +- 16.99 (95%)
Games | N: 1084 W: 437 L: 278 D: 369
```
```
ELO   | 3.25 +- 5.51 (95%)
Games | N: 9616 W: 3084 L: 2994 D: 3538
```

Remove instances of shared memory

---

Halogen/src/Search.cpp

Bench: 6111232
```
ELO   | 6.77 +- 5.03 (95%)
Games | N: 11296 W: 3596 L: 3376 D: 4324
```

No tt in pv

---

Halogen/src/main.cpp

Bench: 6144000
```
ELO   | 27.22 +- 11.90 (95%)
SPRT  | 40/10.0s Threads=1 Hash=8MB
Games | N: 2136 W: 776 L: 609 D: 751
```

More evenly allocate time

---

Halogen/src/main.cpp

Bench 6144000
```
ELO   | 14.20 +- 8.32 (95%)
SPRT  | 10.0+0.0s Threads=1 Hash=8MB
Games | N: 4480 W: 1590 L: 1407 D: 1483
```

Sudden death tune

---

Halogen/src/Network.cpp
Halogen/src/Network.h
Halogen/src/Position.cpp
Halogen/src/Position.h
Halogen/src/Search.cpp

Bench: 6144000
```
ELO   | 12.63 +- 7.54 (95%)
Games | N: 4928 W: 1580 L: 1401 D: 1947
```

Use a fixed sized array to increase speed

---

Halogen/src/Search.cpp

```
ELO   | 16.39 +- 8.62 (95%)
LLR   | 3.09 (-2.94, 2.94) [0.00, 5.00]
Games | N: 3712 W: 1190 L: 1015 D: 1507
```

Use more aggressive LMR

---

Halogen/src/Search.cpp

```
ELO   | 4.33 +- 5.95 (95%)
Games | N: 7952 W: 2465 L: 2366 D: 3121
```
```
ELO   | -3.39 +- 3.88 (95%)
LLR   | -1.46 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 14640 W: 3412 L: 3555 D: 7673
```

Basic staged move gen

---

Halogen/src/Search.cpp

Revert "Basic staged move gen"

---

Halogen/src/Search.cpp

```
ELO   | 23.05 +- 9.51 (95%)
Games | N: 2128 W: 512 L: 371 D: 1245
```
```
ELO   | 24.37 +- 10.63 (95%)
LLR   | 3.04 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2256 W: 697 L: 539 D: 1020
```

Bench: 2007040

---

Halogen/src/Search.cpp

```
ELO   | 18.25 +- 8.98 (95%)
Games | N: 2992 W: 857 L: 700 D: 1435
```
```
ELO   | 27.89 +- 10.73 (95%)
Games | N: 1760 W: 455 L: 314 D: 991
```

Futility quadratic 0

---

Halogen/src/Position.cpp
Halogen/src/Search.cpp
Halogen/src/Search.h
Halogen/src/main.cpp

```
ELO   | 0.18 +- 3.18 (95%)
Games | N: 23488 W: 6056 L: 6044 D: 11388
```

Support 'go mate X' UCI command and parse short fen correctly

---

Halogen/src/Position.cpp
Halogen/src/Position.h
Halogen/src/Search.cpp

```
ELO   | 20.75 +- 9.22 (95%)
Games | N: 2464 W: 630 L: 483 D: 1351
```

Futility quick check

---

Halogen/src/TranspositionTable.cpp
Halogen/src/main.cpp

```
ELO   | -2.83 +- 2.23 (95%)
LLR   | -2.95 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 40704 W: 8773 L: 9105 D: 22826
```
Regression likely nonexistant

Fix crash on quit command while searching

---

Halogen/src/BoardParamiters.h
Halogen/src/Position.cpp
Halogen/src/Position.h
Halogen/src/Search.cpp

```
ELO   | 22.66 +- 10.03 (95%)
Games | N: 2272 W: 633 L: 485 D: 1154
```

Fix repetition detection

---

Halogen/src/EvalNet.cpp

```
ELO   | 7.33 +- 5.09 (95%)
Games | N: 8528 W: 2125 L: 1945 D: 4458
```

Give a penalty if the winning side has no pawns

---

Halogen/src/Search.cpp

```
ELO   | 11.57 +- 6.80 (95%)
Games | N: 4896 W: 1280 L: 1117 D: 2499
```

Bench: 11284480

---

Halogen/src/BitBoard.cpp
Halogen/src/BitBoard.h
Halogen/src/BitBoardDefine.cpp
Halogen/src/BitBoardDefine.h
Halogen/src/BoardParamiters.cpp
Halogen/src/BoardParamiters.h
Halogen/src/Move.cpp
Halogen/src/Move.h
Halogen/src/MoveGeneration.cpp
Halogen/src/MoveGeneration.h
Halogen/src/Position.cpp
Halogen/src/Search.cpp

```
ELO   | 5.52 +- 5.72 (95%)
Games | N: 6480 W: 1537 L: 1434 D: 3509
```

Major refactor

---

Halogen/src/Makefile

```
ELO   | 20.88 +- 9.39 (95%)
Games | N: 2416 W: 627 L: 482 D: 1307
```

Use PGO builds by default

---

Halogen/src/BitBoard.cpp
Halogen/src/BitBoardDefine.h
Halogen/src/Position.cpp

```
ELO   | 10.16 +- 6.16 (95%)
Games | N: 5440 W: 1293 L: 1134 D: 3013
```

Small speedup

---

Halogen/Halogen/Halogen.vcxproj
Halogen/Halogen/Halogen.vcxproj.filters
Halogen/src/BoardParameters.cpp
Halogen/src/BoardParameters.h
Halogen/src/Position.cpp
Halogen/src/Position.h
Halogen/src/Search.cpp

```
ELO   | -0.87 +- 1.97 (95%)
Games | N: 53584 W: 11944 L: 12078 D: 29562
```

Fix spelling and add comments

---

Halogen/src/Search.cpp
Halogen/src/Search.h

```
ELO   | 0.07 +- 2.87 (95%)
Games | N: 25428 W: 5771 L: 5766 D: 13891
```
Tested against master with Syzygy enabled locally for non regression

Small cleanups 2

---

Halogen/src/Network.cpp
Halogen/src/Network.h
Halogen/src/Position.cpp
Halogen/src/Position.h

```
ELO   | 5.74 +- 5.82 (95%)
Games | N: 6176 W: 1445 L: 1343 D: 3388
```

Allocate Zeta array on heap

---

Halogen/src/Move.cpp
Halogen/src/Search.cpp
Halogen/src/Search.h
Halogen/src/main.cpp

```
ELO   | 3.63 +- 4.91 (95%)
Games | N: 8704 W: 2022 L: 1931 D: 4751
```

Minor refactor

---

Halogen/src/Search.cpp

Reverts KierenP/Halogen#209
I may have merged the wrong branch :(

Revert "Extend SNMP"

---

Halogen/src/MoveGeneration.cpp
Halogen/src/MoveGeneration.h
Halogen/src/MoveGenerator.cpp
Halogen/src/MoveGenerator.h
Halogen/src/Search.cpp

```
ELO   | 8.94 +- 5.69 (95%)
Games | N: 6336 W: 1488 L: 1325 D: 3523
```

SMG all stages

---

Halogen/src/Move.cpp
Halogen/src/Move.h
Halogen/src/MoveGenerator.cpp

```
ELO   | 6.80 +- 5.12 (95%)
LLR   | 2.97 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 7664 W: 1738 L: 1588 D: 4338
```

Use selection sort

---

Halogen/src/Search.cpp

```
ELO   | 3.54 +- 4.47 (95%)
LLR   | 3.01 (-2.94, 2.94) [-4.00, 1.00]
Games | N: 10208 W: 2306 L: 2202 D: 5700
```

Fix a potential crash

---

Halogen/src/BitBoardDefine.cpp
Halogen/src/BitBoardDefine.h
Halogen/src/MoveGeneration.cpp
Halogen/src/Position.cpp

```
ELO   | 0.32 +- 2.41 (95%)
LLR   | 3.05 (-2.94, 2.94) [-4.00, 1.00]
Games | N: 35088 W: 7745 L: 7713 D: 19630
```

Fix warning and typo

---

Halogen/src/Move.cpp
Halogen/src/Move.h
Halogen/src/SearchData.cpp
Halogen/src/main.cpp

```
ELO   | 12.44 +- 7.15 (95%)
LLR   | 2.99 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 4080 W: 991 L: 845 D: 2244
```

Speed up printing of info to console

---

Halogen/src/Move.cpp
Halogen/src/Move.h
Halogen/src/SearchData.cpp

```
ELO   | 1.03 +- 3.03 (95%)
LLR   | 2.97 (-2.94, 2.94) [-4.00, 1.00]
Games | N: 22368 W: 4993 L: 4927 D: 12448
```

Use string streams for output

---

Halogen/src/MoveGeneration.cpp

Measured speedup: 0.5%
Speed increased from 4.389Mnps to 4.411Mnps during a depth 24 bench (~570m nodes / 130 seconds)

Bench: 32453878

---

Halogen/src/Move.cpp
Halogen/src/Move.h
Halogen/src/MoveGenerator.cpp
Halogen/src/MoveGenerator.h
Halogen/src/Search.cpp
Halogen/src/TTEntry.cpp
Halogen/src/TTEntry.h

```
ELO   | 2.87 +- 4.17 (95%)
LLR   | 2.99 (-2.94, 2.94) [-4.00, 1.00]
Games | N: 11856 W: 2692 L: 2594 D: 6570
```

Refactor move

---

Halogen/src/MoveGenerator.cpp
Halogen/src/Search.cpp
Halogen/src/SearchData.cpp
Halogen/src/SearchData.h

```
ELO   | 3.53 +- 4.76 (95%)
Games | N: 8864 W: 1968 L: 1878 D: 5018
```

Refactor history

---

Halogen/src/MoveGenerator.cpp
Halogen/src/MoveGenerator.h
Halogen/src/SearchData.cpp
Halogen/src/SearchData.h
Halogen/src/TimeManage.h

```
ELO   | 4.50 +- 5.27 (95%)
Games | N: 7328 W: 1661 L: 1566 D: 4101
```

Various small speed and code improvements

---

Halogen/src/BitBoardDefine.cpp
Halogen/src/BitBoardDefine.h

```
ELO   | 0.87 +- 2.59 (95%)
LLR   | -0.32 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 30400 W: 6762 L: 6686 D: 16952
```

Use constexpr for piece attack tables

---

Halogen/src/Network.cpp
Halogen/src/Network.h
Halogen/src/Position.cpp
Halogen/src/Position.h
Halogen/src/main.cpp

```
ELO   | 3.95 +- 4.98 (95%)
Games | N: 8096 W: 1806 L: 1714 D: 4576
```

Reimplement network class

---

Halogen/src/BitBoardDefine.h
Halogen/src/EvalNet.cpp
Halogen/src/Move.h
Halogen/src/MoveGeneration.cpp
Halogen/src/main.cpp
Halogen/src/tbprobe.cpp

```
ELO   | 5.50 +- 5.62 (95%)
Games | N: 6448 W: 1472 L: 1370 D: 3606
```

Fix source of crashes in CCC

---

Halogen/src/Search.cpp

```
ELO   | 1.81 +- 1.86 (95%)
LLR   | 3.00 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 43392 W: 7126 L: 6900 D: 29366
```
```
ELO   | 4.21 +- 3.76 (95%)
LLR   | 2.95 (-2.94, 2.94) [-1.00, 4.00]
Games | N: 14352 W: 3241 L: 3067 D: 8044
```

Expand aspiration windows much slower than before

---

Halogen/src/EvalNet.cpp
Halogen/src/EvalNet.h
Halogen/src/Move.h
Halogen/src/Position.cpp
Halogen/src/Position.h
Halogen/src/Search.cpp
Halogen/src/SearchData.cpp
Halogen/src/SearchData.h

```
ELO   | 2.08 +- 4.03 (95%)
Games | N: 12192 W: 2644 L: 2571 D: 6977
```

Small code improvements

---

Halogen/src/MoveGenerator.cpp
Halogen/src/Search.cpp
Halogen/src/TTEntry.h
Halogen/src/TranspositionTable.cpp
Halogen/src/TranspositionTable.h
Halogen/src/main.cpp

```
ELO   | 3.39 +- 4.03 (95%)
LLR   | 3.04 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 9232 W: 1540 L: 1450 D: 6242
```
```
ELO   | 7.40 +- 6.24 (95%)
SPRT  | 10.0+0.1s Threads=1 Hash=64MB
Games | N: 5024 W: 1115 L: 1008 D: 2901
```

Clean-up code of transposition table

---

Halogen/src/Network.cpp
Halogen/src/Search.cpp

```
ELO   | -0.41 +- 2.31 (95%)
Games | N: 36400 W: 7630 L: 7673 D: 21097
```

Clean-up the network code

---

Halogen/src/BitBoard.cpp
Halogen/src/BitBoard.h
Halogen/src/BitBoardDefine.cpp
Halogen/src/BitBoardDefine.h
Halogen/src/BoardParameters.cpp
Halogen/src/BoardParameters.h
Halogen/src/Network.cpp
Halogen/src/Network.h
Halogen/src/Position.cpp
Halogen/src/Position.h
Halogen/src/TranspositionTable.cpp
Halogen/src/main.cpp

An argument is passed into a function by value. For the purpose of optimization, it can be passed as a constant reference. It may enhance the program's performance, as it is only the address that will be copied instead of the whole class object when calling the function.
In string classes, operators are implemented that allow more efficient string clearing or checking a string for being empty.
The object of the `std::string` class knows the length of the string it is storing, but it is unknown which string it is intended to be compared to. That's why a loop is called for string comparing. A much easier and better way is to simply check that the string length is 0 - it can be done with the help of the `empty()` function.
The `at()` method returns a reference to the container element …

Small enhancement 

---

Halogen/src/MoveGeneration.cpp

```
ELO   | 0.31 +- 2.85 (95%)
Games | N: 23360 W: 4788 L: 4767 D: 13805
```

Cleanup the move generation file

---

Halogen/src/Search.cpp

Use FIFO system for Killer moves (#262)

---

Halogen/src/MoveGenerator.cpp
Halogen/src/Search.cpp
Halogen/src/SearchData.cpp
Halogen/src/SearchData.h

```
ELO   | 2.40 +- 4.13 (95%)
Games | N: 11158 W: 2330 L: 2253 D: 6575
```

Minor refactor to History tables

---

Halogen/src/Benchmark.h
Halogen/src/BitBoard.cpp
Halogen/src/BitBoard.h
Halogen/src/Search.cpp
Halogen/src/Search.h
Halogen/src/SearchData.cpp
Halogen/src/SearchData.h
Halogen/src/TimeManage.cpp
Halogen/src/TimeManage.h
Halogen/src/TranspositionTable.cpp
Halogen/src/TranspositionTable.h

```
ELO   | -0.85 +- 1.85 (95%)
Games | N: 56673 W: 11826 L: 11965 D: 32882
```

Small non-functional refactor

---

Halogen/src/BitBoard.h
Halogen/src/BoardParameters.cpp
Halogen/src/BoardParameters.h
Halogen/src/EvalCache.cpp
Halogen/src/EvalCache.h
Halogen/src/Move.cpp
Halogen/src/Move.h
Halogen/src/MoveGenerator.cpp
Halogen/src/Position.cpp
Halogen/src/Position.h
Halogen/src/Search.h
Halogen/src/SearchData.cpp
Halogen/src/SearchData.h
Halogen/src/TTEntry.cpp
Halogen/src/TTEntry.h
Halogen/src/TranspositionTable.h

```
ELO   | 5.77 +- 5.58 (95%)
Games | N: 6205 W: 1349 L: 1246 D: 3610
```

Small clean-up

---

Halogen/src/MoveGeneration.cpp
Halogen/src/MoveGeneration.h
Halogen/src/MoveGenerator.cpp
Halogen/src/MoveGenerator.h
Halogen/src/main.cpp

```
ELO   | 7.90 +- 5.08 (95%)
LLR   | 3.02 (-2.94, 2.94) [0.00, 5.00]
Games | N: 7306 W: 1571 L: 1405 D: 4330
```

Generate extended move

---

Halogen/src/main.cpp

```
ELO   | 3.59 +- 2.76 (95%)
Games | N: 18507 W: 2907 L: 2716 D: 12884
```
```
ELO   | 8.32 +- 5.26 (95%)
Games | N: 6768 W: 1450 L: 1288 D: 4030
```

Tune incremental time management

---

Halogen/src/EvalCache.cpp
Halogen/src/EvalCache.h
Halogen/src/Move.cpp
Halogen/src/Move.h
Halogen/src/TTEntry.cpp
Halogen/src/main.cpp
HalogenTests/HalogenTests.vcxproj
HalogenTests/HalogenTests.vcxproj.filters
HalogenTests/TestEvalCache.cpp
HalogenTests/TestMoveGeneration.cpp

```
ELO   | 2.18 +- 3.94 (95%)
Games | N: 11792 W: 2368 L: 2294 D: 7130
```

Add more unit tests

---

Halogen/src/BitBoard.h
Halogen/src/MoveGenerator.cpp
Halogen/src/MoveGenerator.h
Halogen/src/main.cpp

Replace the recursive SEE function with an iterative one

Use iterative swap algorithm for static exchange evaluation

---

Halogen/src/BitBoard.cpp
Halogen/src/BitBoard.h

```
Halogen_dev.exe           |         Halogen_master.exe
mu             sigma^2      |        mu             sigma^2           SE      DF      t           p
------------------------------------+------------------------------------
2977000.000             0.000|       2877000.000             0.000|
2962000.000     450000000.000|       2861500.000     480500000.000|   21569.655   1    4.659324    0.134592
2957333.333     290333333.333|       2840666.667    1542333333.333|   24716.167   2    4.720257    0.042070
2958750.000     201583333.333|       2839000.000    1039333333.333|   17613.324   3    6.798830    0.006506
2957000.000     166500000.000|       2840800.000     795700000.000|   13872.275   4    8.376420    0.001111
2958833.333     153366666.667|       2842500.000 …
```

Speedup GetAllPieces function by caching results

---

Halogen/Halogen/Halogen.vcxproj
Halogen/Halogen/Halogen.vcxproj.filters
Halogen/src/MoveGeneration.cpp
Halogen/src/MoveGeneration.h
Halogen/src/MoveGenerator.cpp
Halogen/src/MoveGenerator.h
Halogen/src/MoveList.cpp
Halogen/src/MoveList.h
Halogen/src/Search.cpp
Halogen/src/SearchData.h
Halogen/src/main.cpp

```
ELO   | 6.29 +- 4.39 (95%)
Games | N: 9664 W: 2033 L: 1858 D: 5773
```

Implement a movelist class to recycle and avoid alloations

---

Halogen/src/MoveList.cpp
Halogen/src/MoveList.h
Halogen/src/main.cpp

``` 
Halogen_10.9.5.exe         |         Halogen_10.9.4.exe
mu             sigma^2      |        mu             sigma^2           SE      DF      t           p
------------------------------------+------------------------------------
3053000.000             0.000|       3065000.000             0.000|
3057000.000      32000000.000|       3064000.000       2000000.000|    4123.106   1   -1.697749    0.338875
3056666.667      16333333.333|       3062000.000      13000000.000|    3126.944   2   -1.705606    0.230200
3052000.000      98000000.000|       3061250.000      10916666.667|    5218.157   3   -1.772656    0.174400
3054400.000     102300000.000|       3062200.000      12700000.000|    4795.832   4   -1.626412    0.179190
3055500.000      89100000.000|       3063333.333 …
```

Clean-up new MoveList class

---

Halogen/src/Search.cpp

```
ELO   | 1.24 +- 1.62 (95%)
LLR   | -1.66 (-2.94, 2.94) [0.00, 5.00]
Games | N: 70056 W: 14095 L: 13845 D: 42116
```

Do not do futility pruning if I am being checkmated

---

Halogen/src/MoveGeneration.cpp
Halogen/src/MoveGeneration.h
Halogen/src/MoveGenerator.cpp
Halogen/src/MoveGenerator.h
Halogen/src/MoveList.cpp
Halogen/src/MoveList.h
Halogen/src/Search.cpp
Halogen/src/main.cpp

```
ELO   | 6.22 +- 5.66 (95%)
Games | N: 5808 W: 1218 L: 1114 D: 3476
```

Implement a basic move list

---

src/BitBoardDefine.cpp
src/BitBoardDefine.h
src/MoveGenerator.cpp
src/Search.cpp
src/main.cpp

```
ELO   | 0.42 +- 2.64 (95%)
Games | N: 23408 W: 4152 L: 4124 D: 15132
```

Fix code warnings

---

src/EvalNet.cpp
src/EvalNet.h
src/TimeManage.cpp
src/TimeManage.h
src/Zobrist.cpp
src/Zobrist.h
src/main.cpp

```
ELO   | -0.00 +- 2.35 (95%)
Games | N: 30120 W: 5431 L: 5431 D: 19258
```

Small code cleanups

---

src/Network.cpp

```
ELO   | 17.53 +- 8.60 (95%)
GAMES | N: 5000 W: 2117 L: 1865 D: 1018
```

Use safer code for softmax

---

src/Network.cpp

```
ELO   | 44.72 +- 8.03 (95%)
GAMES | N: 5000 W: 2035 L: 1395 D: 1570
```

Change the scale to 300

---

src/MoveGenerator.cpp
src/MoveGenerator.h
src/Search.cpp
src/main.cpp

```
ELO   | 18.47 +- 8.07 (95%)
GAMES | N: 2560 W: 529 L: 393 D: 1638
```

Cleanup code for MoveGenerator

---

src/Move.h
src/MoveGenerator.cpp
src/Position.cpp
src/Position.h
src/SearchData.cpp
src/SearchData.h
src/main.cpp

```
ELO   | 0.48 +- 2.83 (95%)
LLR   | -1.60 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 22264 W: 4312 L: 4281 D: 13671
```

Add move list stack to track previous moves in game

---

src/Network.cpp
src/Network.h
src/Position.cpp
src/Position.h

```
ELO   | 4.08 +- 4.69 (95%)
GAMES | N: 7832 W: 1502 L: 1410 D: 4920
```

New increment network

---

src/BoardParameters.cpp
src/BoardParameters.h
src/Position.cpp
src/Position.h
src/Zobrist.cpp
src/Zobrist.h
src/main.cpp

```
ELO   | 2.56 +- 4.10 (95%)
GAMES | N: 10864 W: 2180 L: 2100 D: 6584
```

Cleanup Zobrist tables

---

src/Network.cpp
src/Network.h
src/Position.cpp
src/Position.h
src/main.cpp

```
ELO   | 0.64 +- 3.01 (95%)
GAMES | N: 19992 W: 3936 L: 3899 D: 12157
```

Clean-up neural network implementation

---

src/Search.cpp
src/main.cpp

```
ELO   | -6.92 +- 4.55 (95%)
LLR   | -2.94 (-2.94, 2.94) [-5.00, 0.00]
GAMES | N: 7880 W: 1309 L: 1466 D: 5105
```

Fix potential for illegal moves under extreme time pressure

---

.github/workflows/main.yml
src/Search.cpp
src/SearchLimits.cpp
src/SearchLimits.h
src/main.cpp

Support 'go nodes X' UCI commands

---

src/main.cpp

```
ELO   | 227.35 +- 4.35 (95%)
GAMES | N: 20000 W: 12669 L: 1177 D: 6154
```
```
ELO   | 213.95 +- 8.16 (95%)
CONF  | 5.0+0.05s Threads=8 Hash=64MB
GAMES | N: 5000 W: 2981 L: 240 D: 1779
```
```
ELO   | 228.91 +- 8.17 (95%)
CONF  | 40.0+0.40s Threads=1 Hash=64MB
GAMES | N: 5000 W: 3057 L: 169 D: 1774
```
```
ELO   | 184.88 +- 16.27 (95%)
CONF  | 20.0+0.20s Threads=8 Hash=256MB
GAMES | N: 1000 W: 521 L: 34 D: 445
```

Release canditate for Halogen 11

---

src/BoardState.cpp
src/BoardState.h
src/GameState.cpp
src/Search.cpp
src/SearchData.cpp
src/StagedMoveGenerator.cpp
src/main.cpp

```
ELO   | -2.78 +- 13.16 (95%)
GAMES | N: 1000 W: 183 L: 191 D: 626
```
Tested for non-regression. Master currently crashes when probing the EGTB.

Fix EGTB probing, small bug fixes and improvements

---

src/BitBoardDefine.h
src/EvalCache.cpp
src/EvalCache.h
src/EvalNet.cpp
src/EvalNet.h
src/GameState.cpp
src/GameState.h
src/Makefile
src/MoveList.h
src/Network.cpp
src/Network.h
src/Score.cpp
src/Score.h
src/Search.cpp
src/Search.h
src/SearchData.cpp
src/SearchData.h
src/SearchLimits.cpp
src/SearchLimits.h
src/TTEntry.cpp
src/TTEntry.h
src/TranspositionTable.cpp
src/TranspositionTable.h

```
Elo   | -0.78 +- 1.95 (95%)
Games | N: 62666 W: 16146 L: 16286 D: 30234
Penta | [788, 7177, 15492, 7139, 737]
```

Add new Score class to replace int16 type

---

src/Search.cpp
src/StagedMoveGenerator.cpp
src/StagedMoveGenerator.h
src/TTEntry.cpp
src/TTEntry.h
src/TranspositionTable.cpp
src/TranspositionTable.h
src/main.cpp

```
Elo   | 5.18 +- 6.82 (95%)
LLR   | 2.41 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 4894 W: 1240 L: 1167 D: 2487
Penta | [38, 552, 1197, 619, 41]
```

Refactor TT implementation

---

src/GameState.cpp
src/GameState.h
src/Search.cpp
src/Search.h
src/SearchData.cpp
src/SearchData.h
src/StagedMoveGenerator.cpp
src/StagedMoveGenerator.h
src/TimeManage.h
src/main.cpp

```
Elo   | -3.79 +- 3.60 (95%)
LLR   | -2.99 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 18526 W: 4710 L: 4912 D: 8904
Penta | [265, 2309, 4303, 2135, 251]
```
Small elo loss, but a good change.

Rewrite the search state implementation to use a search stack

---

src/EvalNet.cpp
src/Network.cpp
src/Search.cpp
src/main.cpp

Simply score handling by using relative scores everywhere

---

src/Search.cpp
src/main.cpp

Template search type

---

src/Search.cpp

```
Elo   | 0.16 +- 2.65 (95%)
LLR   | -2.99 (-2.94, 2.94) [0.00, 5.00]
Games | N: 32494 W: 8043 L: 8028 D: 16423
Penta | [399, 3893, 7615, 3974, 366]
http://chess.grantnet.us/test/36546/
```

Adjust LMR reduction to fit more generically within the search

---

src/Search.cpp
src/StagedMoveGenerator.cpp
src/TTEntry.cpp
src/TTEntry.h
src/TranspositionTable.cpp

```
$ python3 ./speedup.py 
Halogen-11.11.1.exe         |       Halogen-pext-avx2.exe        |
mu              sigma       |        mu              sigma       |   Sp(1)/Sp(2)      3*sigma   
------------------------------------+------------------------------------+------------------------------------
4037176.471          2173.480|       4037696.078          2093.606|      -0.011 %  +/-  0.177 %
```
No speed difference

Refactor TT entries

---

src/Search.cpp
src/TTEntry.h
src/TranspositionTable.cpp

```
$ python3 speedup.py 
Halogen-11.11.1.exe         |       Halogen-pext-avx2.exe        |
mu              sigma       |        mu              sigma       |   Sp(1)/Sp(2)      3*sigma   
------------------------------------+------------------------------------+------------------------------------
5047337.864          2388.878|       5030013.592          1768.348|       0.348 %  +/-  0.145 %
```
0.3% slowdown.

Use atomics in TT

---

.github/workflows/regression_check.yml
src/History.cpp
src/History.h
src/Makefile
src/Search.cpp
src/SearchData.cpp
src/SearchData.h
src/StagedMoveGenerator.cpp

```
Elo   | 5.48 +- 6.09 (95%)
LLR   | 3.11 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 6086 W: 1533 L: 1437 D: 3116
Penta | [52, 664, 1544, 702, 81]
http://chess.grantnet.us/test/36683/
```

Refactor history implementation

---

src/Search.cpp
src/main.cpp

```
Elo   | 5.58 +- 4.72 (95%)
Games | N: 9964 W: 2470 L: 2310 D: 5184
Penta | [105, 1143, 2354, 1247, 133]
http://chess.grantnet.us/test/36753/
```
```
Elo   | 8.24 +- 6.10 (95%)
Games | N: 6030 W: 1534 L: 1391 D: 3105
Penta | [63, 660, 1440, 775, 77]
http://chess.grantnet.us/test/36749/
```

Apply LMR scheme after 3 moves

---

src/Search.cpp
src/SearchData.cpp
src/SearchData.h

```
Elo   | 0.84 +- 3.57 (95%)
Games | N: 17748 W: 4358 L: 4315 D: 9075
Penta | [181, 1979, 4553, 1938, 223]
http://chess.grantnet.us/test/36782/
```

Refactor parts of the search

---

src/BitBoardDefine.h
src/BoardState.cpp
src/BoardState.h
src/EGTB.cpp
src/EvalNet.cpp
src/MoveGeneration.cpp
src/StagedMoveGenerator.cpp
src/main.cpp

Before:
```
Completed perft with: 126/126 correct
Total nodes: 4.58092e+09 in 49.3371s
Nodes per second: 92849527
```
After:
```
Completed perft with: 126/126 correct
Total nodes: 4.58092e+09 in 48.5632s
Nodes per second: 94329081
```
Speedup 1.6%

Cleanup movegen

---

.github/workflows/regression_check.yml
src/BitBoardDefine.h
src/EGTB.h
src/EvalCache.cpp
src/GameState.cpp
src/GameState.h
src/History.h
src/Makefile
src/MoveGeneration.h
src/MoveList.h
src/Network.cpp
src/Score.h
src/Search.cpp
src/Search.h
src/SearchData.cpp
src/SearchData.h
src/StagedMoveGenerator.cpp
src/StagedMoveGenerator.h
src/StaticVector.h
src/TTEntry.cpp
src/TTEntry.h
src/TimeManage.cpp
src/TranspositionTable.cpp
src/TranspositionTable.h
src/main.cpp

```
Elo   | 5.96 +- 4.10 (95%)
Games | N: 8926 W: 2281 L: 2128 D: 4517
Penta | [86, 1005, 2148, 1118, 106]
http://chess.grantnet.us/test/36800/
```

Add PGO compile

---

src/Benchmark.h
src/TTEntry.cpp
src/main.cpp

```
Elo   | 1.11 +- 3.03 (95%)
Games | N: 15976 W: 3872 L: 3821 D: 8283
Penta | [179, 1792, 3987, 1859, 171]
http://chess.grantnet.us/test/36808/
```

Fix TT mate scores

---

src/Search.cpp
src/SearchData.cpp
src/SearchData.h
src/main.cpp

```
Elo   | 4.43 +- 11.64 (95%)
LLR   | 0.47 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 1098 W: 283 L: 269 D: 546
Penta | [8, 126, 278, 118, 19]
http://chess.grantnet.us/test/36878/
```

Fix multi PV mostly

---

.github/workflows/cross-platform-checl.yml
.github/workflows/regression-check.yml
.github/workflows/regression_check.yml
src/History.h
src/Makefile
src/main.cpp

Tested the history cap patch:
```
Elo   | 4.25 +- 4.32 (95%)
Games | N: 6698 W: 1558 L: 1476 D: 3664
Penta | [31, 723, 1774, 775, 46]
http://chess.grantnet.us/test/36927/
```
```
Elo   | 1.03 +- 2.99 (95%)
Games | N: 16594 W: 4146 L: 4097 D: 8351
Penta | [170, 1919, 4107, 1894, 207]
http://chess.grantnet.us/test/36926/
```

Fix thread sanitizer

---

.github/workflows/regression_check.yml
src/EGTB.cpp
src/EGTB.h
src/Search.cpp
src/main.cpp

```
Elo   | 0.59 +- 1.88 (95%)
Games | N: 20000 W: 4029 L: 3995 D: 11976
Penta | [15, 1459, 7013, 1503, 10]
http://chess.grantnet.us/test/36922/
```

Use tb_probe_root_dtz to sort root moves

---

.github/workflows/regression-check.yml
src/Benchmark.h
src/BoardState.cpp
src/BoardState.h
src/EGTB.cpp
src/GameState.cpp
src/GameState.h
src/Makefile
src/Search.cpp
src/SearchData.cpp
src/SearchData.h
src/TranspositionTable.h
src/main.cpp
src/uci/options.h
src/uci/parse.h
src/uci/uci.cpp
src/uci/uci.h
src/uci/validate_callback.h

```
Elo   | -0.05 +- 2.28 (95%)
Games | N: 29996 W: 7568 L: 7572 D: 14856
Penta | [394, 3493, 7203, 3539, 369]
http://chess.grantnet.us/test/37144/
```

Refactor UCI library

---

src/Search.cpp
src/SearchConstants.h

```
Elo   | 8.16 +- 5.98 (95%)
Games | N: 4256 W: 1126 L: 1026 D: 2104
Penta | [44, 451, 1061, 505, 67]
http://chess.grantnet.us/test/37174/
```

Rewrite search algorithm

---

src/Search.cpp
src/SearchConstants.h
src/main.cpp

```
Elo   | 18.60 +- 7.67 (95%)
Games | N: 2188 W: 552 L: 435 D: 1201
Penta | [8, 206, 560, 301, 19]
http://chess.grantnet.us/test/37217/
```
```
Elo   | 25.16 +- 9.34 (95%)
Games | N: 1798 W: 533 L: 403 D: 862
Penta | [16, 165, 422, 265, 31]
http://chess.grantnet.us/test/37216/
```

SPSA LTC tune

---

src/Search.cpp
src/main.cpp

```
Elo   | 0.37 +- 1.23 (95%)
LLR   | -3.01 (-2.94, 2.94) [0.00, 5.00]
Games | N: 46762 W: 9397 L: 9347 D: 28018
Penta | [49, 3369, 16495, 3419, 49]
http://chess.grantnet.us/test/37194/
```

Probe Transposition Table before Syzygy EGTB

---

src/BoardState.cpp
src/EGTB.cpp
src/EGTB.h
src/Move.cpp
src/Score.h
src/Search.cpp
src/main.cpp
src/uci/options.h
src/uci/uci.cpp
src/uci/uci.h

```
Elo   | 0.56 +- 2.73 (95%)
Games | N: 20634 W: 5198 L: 5165 D: 10271
Penta | [244, 2404, 5025, 2363, 281]
http://chess.grantnet.us/test/37225/
```
Minimal vs Default mode:
```
Elo   | 6.17 +- 2.72 (95%)
Games | N: 20000 W: 5126 L: 4771 D: 10103
Penta | [196, 2193, 4911, 2460, 240]
http://chess.grantnet.us/test/37227/
```

Add eval, probe, OutputLevel uci extensions

---

src/TTEntry.cpp
src/TTEntry.h

```
Elo   | 4.72 +- 4.82 (95%)
Games | N: 6926 W: 1791 L: 1697 D: 3438
Penta | [91, 774, 1655, 836, 107]
http://chess.grantnet.us/test/37343/
```

Fix generation calculation

---

src/GameState.cpp
src/Makefile
src/Network.cpp
src/Network.h
src/main.cpp

```
File Path      : ...
Threads        : 20
WDL Proportion : start 0.3 end 0.3
Max Epochs     : 50
Save Rate      : 10
Batch Size     : 16384
Net Name       : bullet_r18_768-512x2-1x8
LR Scheduler   : start 0.001 gamma 0.95 drop every 1 epochs
Scale          : 160
Positions      : 1116214793
```
```
Elo   | 5.00 +- 3.71 (95%)
Games | N: 13058 W: 3684 L: 3496 D: 5878
Penta | [222, 1531, 2860, 1669, 247]
http://chess.grantnet.us/test/37556/
```
```
Elo   | 2.71 +- 2.17 (95%)
Games | N: 31572 W: 8160 L: 7914 D: 15498
Penta | [285, 3787, 7417, 3991, 306]
http://chess.grantnet.us/test/37558/
```

Update default network to c61a0069.nn

---

src/Network.cpp
src/Network.h
src/main.cpp

Non-functional speedup
```
Elo   | 7.89 +- 4.88 (95%)
Games | N: 6384 W: 1694 L: 1549 D: 3141
Penta | [76, 670, 1558, 809, 79]
http://chess.grantnet.us/test/37574/
```

Avoid recalculating the non-stm accumulator

---

src/Network.cpp
src/Network.h

```
Elo   | 8.62 +- 5.15 (95%)
Games | N: 5646 W: 1443 L: 1303 D: 2900
Penta | [51, 623, 1351, 731, 67]
http://chess.grantnet.us/test/37577/
```

Implement Finny tables

---

src/Network.cpp
src/Network.h
src/main.cpp

Speedup: `-2.379 %  +/-  0.245 %`
```
Elo   | 2.49 +- 1.99 (95%)
Games | N: 37042 W: 9299 L: 9033 D: 18710
Penta | [366, 4269, 9001, 4503, 382]
http://chess.grantnet.us/test/37588/
```

Implement fused accumulator updates

---

src/Evaluate.cpp
src/Evaluate.h
src/Network.cpp
src/Network.h
src/Search.cpp
src/SearchData.cpp
src/main.cpp

```
Elo   | 9.21 +- 5.31 (95%)
Games | N: 5322 W: 1379 L: 1238 D: 2705
Penta | [55, 559, 1305, 674, 68]
http://chess.grantnet.us/test/37631/
```
```
Elo   | 7.73 +- 4.65 (95%)
Games | N: 5710 W: 1407 L: 1280 D: 3023
Penta | [27, 583, 1515, 696, 34]
http://chess.grantnet.us/test/37632/
```
```
Elo   | 14.37 +- 6.78 (95%)
LLR   | 2.94 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2976 W: 770 L: 647 D: 1559
Penta | [15, 307, 734, 404, 28]
http://chess.grantnet.us/test/37633/
```
```
Elo   | 10.08 +- 4.87 (95%)
Conf  | 20.0+0.20s Threads=8 Hash=256MB
Games | N: 5000 W: 1170 L: 1025 D: 2805
Penta | [9, 520, …
```

Implement lazy accumulator updates

---

src/Makefile
src/Network.h
src/main.cpp

```
Elo   | 6.03 +- 4.08 (95%)
Games | N: 8524 W: 2280 L: 2132 D: 4112
Penta | [58, 976, 2072, 1072, 84]
http://chess.grantnet.us/test/37664/
```
```
Elo   | 6.63 +- 4.49 (95%)
Games | N: 8488 W: 2399 L: 2237 D: 3852
Penta | [114, 995, 1900, 1085, 150]
http://chess.grantnet.us/test/37663/
```

Update default network to 6faaebee.nn

---

src/main.cpp

```
Elo   | 160.06 +- 7.13 (95%)
Games | N: 5004 W: 2467 L: 312 D: 2225
Penta | [7, 125, 674, 1098, 598]
http://chess.grantnet.us/test/37692/
```
```
Elo   | 137.47 +- 6.17 (95%)
Conf  | 40.0+0.40s Threads=1 Hash=64MB
Games | N: 5026 W: 2092 L: 201 D: 2733
Penta | [2, 94, 848, 1149, 420]
http://chess.grantnet.us/test/37699/
```
```
Elo   | 183.42 +- 6.92 (95%)
Conf  | 5.0+0.05s Threads=8 Hash=64MB
Games | N: 5000 W: 2587 L: 168 D: 2245
Penta | [1, 66, 580, 1219, 634]
http://chess.grantnet.us/test/37700/
```
```
Elo   | 145.05 +- 6.20 (95%)
Conf  | 40/40.0+0.00s Threads=1 Hash=64MB
Games | N: 5000 W: 2154 L: 180 D: 2666
Penta | [3, 64, 836, 1150, 447]
http://chess.grantnet.us/test/37701/
```
```
Elo   | 175.06 +- 7.33 (95%)
Conf  | 8.0+0.08s Threads=8 …
```

Halogen 12 release

---

src/Search.cpp
src/main.cpp

```
Elo   | 2.43 +- 3.48 (95%)
Games | N: 9716 W: 2252 L: 2184 D: 5280
Penta | [26, 1094, 2548, 1166, 24]
http://chess.grantnet.us/test/37737/
```
```
Elo   | 0.72 +- 1.54 (95%)
LLR   | -3.02 (-2.94, 2.94) [0.00, 5.00]
Games | N: 60896 W: 14940 L: 14813 D: 31143
Penta | [548, 7206, 14796, 7367, 531]
http://chess.grantnet.us/test/37735/
```

Enter q-search at start of search function

---

.github/workflows/regression-check.yml
src/Makefile
src/Network.cpp
src/SearchData.cpp
src/SearchData.h
src/TTEntry.cpp
src/main.cpp

```
Elo   | -0.56 +- 1.66 (95%)
Games | N: 49106 W: 11836 L: 11915 D: 25355
Penta | [401, 5602, 12626, 5523, 401]
http://chess.grantnet.us/test/37751/
```

Fix various integer overflow issues

---

src/Search.cpp
src/main.cpp

Cleanup excluded_search handling in search

---

src/BoardState.cpp
src/BoardState.h
src/MoveGeneration.cpp
src/main.cpp

Perft before: `253972900 nps` after: `310658665 nps`

Speedup Movegen function

---

src/Makefile
src/main.cpp

```
Elo   | 1.77 +- 2.53 (95%)
Games | N: 20002 W: 4862 L: 4760 D: 10380
Penta | [125, 2204, 5251, 2286, 135]
http://chess.grantnet.us/test/38204/
```

Upgrade to C++20

---

src/History.cpp
src/History.h
src/Search.cpp
src/SearchData.cpp
src/SearchData.h
src/StagedMoveGenerator.cpp

```
Elo   | 2.12 +- 3.45 (95%)
Games | N: 10988 W: 2751 L: 2684 D: 5553
Penta | [67, 1222, 2878, 1231, 96]
http://chess.grantnet.us/test/38304/
```
Speedup: `1.373 %  +/-  0.171 %`

Refactor continuation history heuristic

---

src/Search.cpp
src/Search.h
src/SearchData.cpp
src/SearchData.h

```
Elo   | 0.05 +- 1.34 (95%)
LLR   | 2.97 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 74958 W: 18713 L: 18702 D: 37543
Penta | [603, 8479, 19288, 8522, 587]
http://chess.grantnet.us/test/38307/
```

Extract the bestmove from the root PV

---

src/Cuckoo.cpp
src/Cuckoo.h
src/GameState.cpp
src/GameState.h
src/Makefile
src/Search.cpp
src/Zobrist.h
src/main.cpp

```
Elo   | 3.09 +- 2.19 (95%)
Games | N: 28368 W: 6969 L: 6717 D: 14682
Penta | [174, 3317, 6962, 3545, 186]
```

Use Cuckoo hash table to detect upcoming repetitions

---

src/BoardState.cpp
src/BoardState.h
src/Cuckoo.cpp
src/GameState.cpp
src/Zobrist.cpp
src/Zobrist.h
src/main.cpp

```
Elo   | 1.58 +- 2.25 (95%)
LLR   | 2.98 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 27268 W: 6642 L: 6518 D: 14108
Penta | [198, 3216, 6677, 3350, 193]
```

Refactor Zobrist hashing

---

src/BitBoardDefine.h
src/MoveGeneration.cpp
src/main.cpp

Tested with `taskset -c 1 ../bin/Halogen-native "position fen r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - " "perft 7"`
master:
`Nodes searched: 374190009323 in 992.808 seconds (376900783 nps)`
dev:
`Nodes searched: 374190009323 in 984.459 seconds (380097018 nps)`

Implement 'RayBB' to use in movegen

---

src/StagedMoveGenerator.cpp
src/main.cpp

Speedup: `0.131 %  +/-  0.094 %`

Refine partial sort algorithm

---

src/BitBoardDefine.h
src/Move.h
src/Search.cpp
src/StagedMoveGenerator.h
src/uci/uci.h

Speedup: `0.334 %  +/-  0.160 `

Use explicit enum types to decrease structure sizes

---

src/Search.cpp
src/main.cpp
src/test/tsan.supp

```
Elo   | 1.50 +- 1.21 (95%)
Games | N: 88454 W: 21625 L: 21244 D: 45585
Penta | [555, 9863, 23006, 10252, 551]
http://chess.grantnet.us/test/39142/
```

Don't evaluate the position when in check

---

src/main.cpp

Elo gain to Halogen 12:
```
Elo   | 112.92 +- 6.27 (95%)
Conf  | 40.0+0.40s Threads=1 Hash=8MB
Games | N: 3436 W: 1177 L: 98 D: 2161
Penta | [0, 40, 720, 797, 161]
http://chess.grantnet.us/test/39622/
```

Halogen 13 release

---

src/chessboard/board_state.cpp
src/chessboard/board_state.h
src/datagen/encode.cpp
src/evaluation/evaluate.cpp
src/main.cpp
src/movegen/movegen.cpp
src/search/static_exchange_evaluation.cpp
src/search/syzygy.cpp
src/search/zobrist.cpp

With modern compilers we can rely on constant propagation and inlining
Speed diff: `0.100 %  +/-  0.472 %`

Remove templated get_pieces_bb functions

---

src/Makefile
src/main.cpp
src/network/network.h

```
Elo   | 10.13 +- 4.27 (95%)
Games | N: 6384 W: 1631 L: 1445 D: 3308
Penta | [12, 661, 1662, 843, 14]
http://chess.grantnet.us/test/39736/
```
```
Elo   | 4.75 +- 2.88 (95%)
Games | N: 16234 W: 4039 L: 3817 D: 8378
Penta | [100, 1843, 4016, 2051, 107]
http://chess.grantnet.us/test/39735/
```

Update default network to c73b45d8.nn

---

src/main.cpp
src/search/search.cpp

```
Elo   | 3.72 +- 2.44 (95%)
Games | N: 21218 W: 5151 L: 4924 D: 11143
Penta | [89, 2433, 5335, 2666, 86]
http://chess.grantnet.us/test/39906/
```

Increase RFP margin for positions with active threats that need to be resolved

---

src/main.cpp
src/search/data.h
src/search/history.cpp
src/search/history.h
src/search/search.cpp

```
Elo   | 1.98 +- 1.56 (95%)
Games | N: 52410 W: 12696 L: 12398 D: 27316
Penta | [225, 6134, 13214, 6382, 250]
http://chess.grantnet.us/test/39925/
```

Add Continuation Correction History

---

src/main.cpp

Halogen 15 release

---

src/chessboard/game_state.cpp
src/chessboard/game_state.h
src/main.cpp
src/search/syzygy.cpp
src/search/syzygy.h
src/search/thread.cpp
src/uci/uci.cpp

```
Elo   | 1.62 +- 2.03 (95%)
LLR   | 2.98 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 23798 W: 5791 L: 5680 D: 12327
Penta | [60, 2206, 7259, 2311, 63]
http://chess.grantnet.us/test/40116/
```

Make EGTB probing aware of repeated positions
